fix UT

diff --git a/bin/cli b/bin/cli
--- a/bin/cli
+++ b/bin/cli
@@ -78,7 +78,7 @@ Log::displaySuccess() {
 # * $@ command with arguments to execute
 Framework::run() {
   # 'bash_framework_status', 'bash_framework_duration' are global variables
-  local -i start, end
+  local -i start end
   start=$(date +%s)
   bash_framework_status=0
   bash_framework_output=""
@@ -104,7 +104,9 @@ Framework::run() {
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_DEBUG)); then
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+  fi
 }
 
 # Display message using error color (red)
@@ -242,7 +244,6 @@ Assert::commandExists() {
   local commandName="$1"
   local helpIfNotExists="$2"
 
-  Log::displayInfo "check ${commandName} installed"
   command -v "${commandName}" >/dev/null 2>/dev/null || {
     Log::displayError "${commandName} is not installed, please install it"
     if [[ -n "${helpIfNotExists}" ]]; then
@@ -296,7 +297,7 @@ Database::checkDsnFile() {
 
   (
     unset HOSTNAME PORT PASSWORD USER
-    # shellcheck source=tests/data/dsn_valid.env
+    # shellcheck source=/tests/data/dsn_valid.env
     source "${DSN_FILENAME}"
     if [[ -z ${HOSTNAME+x} ]]; then
       Log::displayError "dsn file ${DSN_FILENAME} : HOSTNAME not provided"
@@ -407,10 +408,10 @@ Framework::loadEnv() {
   if [[ -z "${BASH_FRAMEWORK_ENV_FILEPATH+xxx}" ]]; then
     # BASH_FRAMEWORK_ENV_FILEPATH not defined
     if [[ -f "${HOME}/.bash-tools/.env" ]]; then
-      # shellcheck source=tests/data/.env
+      # shellcheck source=/tests/data/.env
       source "${HOME}/.bash-tools/.env" || exit 1
     elif [[ -f "${HOME}/.env" ]]; then
-      # shellcheck source=tests/data/.env
+      # shellcheck source=/tests/data/.env
       source "${HOME}/.env" || exit 1
     fi
   elif [[ -z "${BASH_FRAMEWORK_ENV_FILEPATH}" ]]; then
@@ -420,7 +421,7 @@ Framework::loadEnv() {
     # load BASH_FRAMEWORK_ENV_FILEPATH
     [[ ! -f "${BASH_FRAMEWORK_ENV_FILEPATH}" ]] &&
       Log::fatal "env file not not found - ${BASH_FRAMEWORK_ENV_FILEPATH}"
-    # shellcheck source=tests/data/.env
+    # shellcheck source=/tests/data/.env
     source "${BASH_FRAMEWORK_ENV_FILEPATH}"
   fi
 
@@ -433,45 +434,56 @@ Framework::loadEnv() {
 
 if [[ -t 1 || -t 2 ]]; then
   # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  export readonly __ERROR_COLOR='\e[31m'      # Red
-  export readonly __INFO_COLOR='\e[44m'       # white on lightBlue
-  export readonly __SUCCESS_COLOR='\e[32m'    # Green
-  export readonly __WARNING_COLOR='\e[33m'    # Yellow
-  export readonly __SKIPPED_COLOR='\e[93m'    # Light Yellow
-  export readonly __TEST_COLOR='\e[100m'      # Light magenta
-  export readonly __TEST_ERROR_COLOR='\e[41m' # white on red
-  export readonly __SKIPPED_COLOR='\e[33m'    # Yellow
-  export readonly __DEBUG_COLOR='\e[37m'      # Grey
+  readonly __ERROR_COLOR='\e[31m'      # Red
+  readonly __INFO_COLOR='\e[44m'       # white on lightBlue
+  readonly __SUCCESS_COLOR='\e[32m'    # Green
+  readonly __WARNING_COLOR='\e[33m'    # Yellow
+  readonly __TEST_COLOR='\e[100m'      # Light magenta
+  readonly __TEST_ERROR_COLOR='\e[41m' # white on red
+  readonly __SKIPPED_COLOR='\e[33m'    # Yellow
+  readonly __DEBUG_COLOR='\e[37m'      # Grey
   # Internal: reset color
-  export readonly __RESET_COLOR='\e[0m' # Reset Color
+  readonly __RESET_COLOR='\e[0m' # Reset Color
   # shellcheck disable=SC2155,SC2034
-  export readonly __HELP_EXAMPLE="$(echo -e "\e[1;30m")"
+  readonly __HELP_EXAMPLE="$(echo -e "\e[1;30m")"
   # shellcheck disable=SC2155,SC2034
-  export readonly __HELP_TITLE="$(echo -e "\e[1;37m")"
+  readonly __HELP_TITLE="$(echo -e "\e[1;37m")"
   # shellcheck disable=SC2155,SC2034
-  export readonly __HELP_NORMAL="$(echo -e "\033[0m")"
+  readonly __HELP_NORMAL="$(echo -e "\033[0m")"
 else
   # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  export readonly __ERROR_COLOR=''
-  export readonly __INFO_COLOR=''
-  export readonly __SUCCESS_COLOR=''
-  export readonly __WARNING_COLOR=''
-  export readonly __SKIPPED_COLOR=''
-  export readonly __TEST_COLOR=''
-  export readonly __TEST_ERROR_COLOR=''
-  export readonly __SKIPPED_COLOR=''
-  export readonly __DEBUG_COLOR=''
+  readonly __ERROR_COLOR=''
+  readonly __INFO_COLOR=''
+  readonly __SUCCESS_COLOR=''
+  readonly __WARNING_COLOR=''
+  readonly __SKIPPED_COLOR=''
+  readonly __TEST_COLOR=''
+  readonly __TEST_ERROR_COLOR=''
+  readonly __DEBUG_COLOR=''
   # Internal: reset color
-  export readonly __RESET_COLOR=''
-  export readonly __HELP_EXAMPLE=''
-  export readonly __HELP_TITLE=''
-  export readonly __HELP_NORMAL=''
+  readonly __RESET_COLOR=''
+  readonly __HELP_EXAMPLE=''
+  readonly __HELP_TITLE=''
+  readonly __HELP_NORMAL=''
 fi
+export __ERROR_COLOR
+export __INFO_COLOR
+export __SUCCESS_COLOR
+export __WARNING_COLOR
+export __SKIPPED_COLOR
+export __TEST_COLOR
+export __TEST_ERROR_COLOR
+export __SKIPPED_COLOR
+export __DEBUG_COLOR
+export __RESET_COLOR
+export __HELP_EXAMPLE
+export __HELP_TITLE
+export __HELP_NORMAL
 
 # Display message using error color (red) and exit immediately with error status 1
 # @param {String} $1 message
 Log::fatal() {
-  Log::displayError "$1"
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
   exit 1
 }
 
@@ -620,9 +632,6 @@ Framework::loadEnv
 # ensure that Ctrl-C is trapped by this script
 trap 'exit 130' INT
 
-# check dependencies
-Assert::commandExists docker "check https://docs.docker.com/engine/install/ubuntu/"
-
 SCRIPT_NAME=${0##*/}
 PROFILES_DIR="${ROOT_DIR}/conf/cliProfiles"
 HOME_PROFILES_DIR="${HOME}/.bash-tools/cliProfiles"
@@ -710,6 +719,9 @@ fi
 if shift; then
   commandArg=("$@")
 fi
+
+# check dependencies
+Assert::commandExists docker "check https://docs.docker.com/engine/install/ubuntu/"
 
 # load default conf file
 Profiles::loadConf "cliProfiles" "default"
diff --git a/bin/dbScriptOneDatabase b/bin/dbScriptOneDatabase
--- a/bin/dbScriptOneDatabase
+++ b/bin/dbScriptOneDatabase
@@ -66,7 +66,9 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+  if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_DEBUG)); then
+    echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
+  fi
 }
 
 # Display message using error color (red)
@@ -143,7 +145,7 @@ Database::checkDsnFile() {
 # * $@ command with arguments to execute
 Framework::run() {
   # 'bash_framework_status', 'bash_framework_duration' are global variables
-  local -i start, end
+  local -i start end
   start=$(date +%s)
   bash_framework_status=0
   bash_framework_output=""
@@ -169,7 +171,7 @@ Framework::run() {
 # Display message using error color (red) and exit immediately with error status 1
 # @param {String} $1 message
 Log::fatal() {
-  Log::displayError "$1"
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
   exit 1
 }
 
@@ -475,10 +477,10 @@ Framework::loadEnv() {
   if [[ -z "${BASH_FRAMEWORK_ENV_FILEPATH+xxx}" ]]; then
     # BASH_FRAMEWORK_ENV_FILEPATH not defined
     if [[ -f "${HOME}/.bash-tools/.env" ]]; then
-      # shellcheck source=tests/data/.env
+      # shellcheck source=/tests/data/.env
       source "${HOME}/.bash-tools/.env" || exit 1
     elif [[ -f "${HOME}/.env" ]]; then
-      # shellcheck source=tests/data/.env
+      # shellcheck source=/tests/data/.env
       source "${HOME}/.env" || exit 1
     fi
   elif [[ -z "${BASH_FRAMEWORK_ENV_FILEPATH}" ]]; then
@@ -488,7 +490,7 @@ Framework::loadEnv() {
     # load BASH_FRAMEWORK_ENV_FILEPATH
     [[ ! -f "${BASH_FRAMEWORK_ENV_FILEPATH}" ]] &&
       Log::fatal "env file not not found - ${BASH_FRAMEWORK_ENV_FILEPATH}"
-    # shellcheck source=tests/data/.env
+    # shellcheck source=/tests/data/.env
     source "${BASH_FRAMEWORK_ENV_FILEPATH}"
   fi
 
