Applied bash-tools-Framework update
Features:
- installRequirements now copies necessary binaries from framework
- build.sh parallelization
- added precommit fixShebangExecutionBit

Fixes:
- fix issue when bash-tools-framework dir does not exists yet
- fix doc - buildPushDockerImages from framework
- updated framework
  - framework refact Profiles::* to Conf::*
  - fixed REPOSITORY_URL + removed author.tpl

diff --git a/bin/cli b/bin/cli
--- a/bin/cli
+++ b/bin/cli
@@ -164,6 +164,135 @@ Assert::windows() {
   fi
 }
 
+# Public: get absolute conf file from specified conf folder deduced using these rules
+#   * from absolute file (ignores <confFolder> and <extension>)
+#   * relative to where script is executed (ignores <confFolder> and <extension>)
+#   * from home/.bash-tools/<confFolder>
+#   * from framework conf/<confFolder>
+#
+# **Arguments**:
+# * $1 confFolder the directory name (not the path) to list
+# * $2 conf file to use without extension
+# * $3 the extension (sh by default)
+#
+# Returns absolute conf filename
+Conf::getAbsoluteFile() {
+  local confFolder="$1"
+  local conf="$2"
+  local extension="${3-.sh}"
+  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
+    extension=".${extension}"
+  fi
+
+  testAbs() {
+    local result
+    result="$(realpath -e "$1" 2>/dev/null)"
+    # shellcheck disable=SC2181
+    if [[ "$?" = "0" && -f "${result}" ]]; then
+      echo "${result}"
+      return 0
+    fi
+    return 1
+  }
+
+  # conf is absolute file (including extension)
+  testAbs "${confFolder}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${confFolder}" && return 0
+  # conf is absolute file (including extension)
+  testAbs "${conf}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${conf}" && return 0
+
+  # relative to where script is executed (including extension)
+  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
+    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
+  fi
+  # from home/.bash-tools/<confFolder>
+  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
+
+  if [[ -n "${ROOT_DIR+xxx}" ]]; then
+    # from framework conf/<confFolder> (including extension)
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
+
+    # from framework conf/<confFolder>
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
+  fi
+
+  # file not found
+  Log::displayError "conf file '${conf}' not found"
+
+  return 1
+}
+
+# Public: list the conf files list available in bash-tools/conf/<conf> folder
+# and those overridden in ${HOME}/.bash-tools/<conf> folder
+# **Arguments**:
+# * $1 confFolder the directory name (not the path) to list
+# * $2 the extension (sh by default)
+# * $3 the indentation ('       - ' by default) can be any string compatible with sed not containing any /
+#
+# **Output**: list of files without extension/directory
+# eg:
+#       - default.local
+#       - default.remote
+#       - localhost-root
+Conf::getMergedList() {
+  local confFolder="$1"
+  local extension="${2:-sh}"
+  local indentStr="${3:-       - }"
+
+  local DEFAULT_CONF_DIR="${ROOT_DIR}/conf/${confFolder}"
+  local HOME_CONF_DIR="${HOME}/.bash-tools/${confFolder}"
+
+  (
+    if [[ -d "${DEFAULT_CONF_DIR}" ]]; then
+      Conf::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+    fi
+    if [[ -d "${HOME_CONF_DIR}" ]]; then
+      Conf::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+    fi
+  ) | sort | uniq
+}
+
+# Public: get absolute file from name deduced using these rules
+#   * using absolute/relative <conf> file (ignores <confFolder> and <extension>
+#   * from home/.bash-tools/<confFolder>/<conf><extension> file
+#   * from framework conf/<conf><extension> file
+#
+# **Arguments**:
+# * $1 confFolder to use below bash-tools conf folder
+# * $2 conf file to use without extension
+# * $3 file extension to use (default: sh)
+#
+# Returns 1 if file not found or error during file loading
+Conf::load() {
+  local confFolder="$1"
+  local conf="$2"
+  local extension="${3:-sh}"
+
+  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
+    extension=".${extension}"
+  fi
+  # if conf is absolute
+  local confFile
+  if [[ "${conf}" == /* ]]; then
+    # file contains /, consider it as absolute filename
+    confFile="${conf}"
+  else
+    # shellcheck source=/conf/dsn/default.local.env
+    confFile="${HOME}/.bash-tools/${confFolder}/${conf}${extension}"
+    if [[ ! -f "${confFile}" ]]; then
+      confFile="${ROOT_DIR}/conf/${confFolder}/${conf}${extension}"
+    fi
+  fi
+  if [[ ! -f "${confFile}" ]]; then
+    return 1
+  fi
+  # shellcheck disable=SC1090
+  source "${confFile}"
+}
+
 # Internal: check if dsn file has all the mandatory variables set
 # Mandatory variables are: HOSTNAME, USER, PASSWORD, PORT
 #
@@ -239,137 +368,41 @@ Log::fatal() {
   exit 1
 }
 
-# shellcheck disable=SC2034
-declare -Ag allDepsResultSeen=()
-declare -ag allDepsResult=()
-
-# Public: get absolute conf file from specified conf folder deduced using these rules
-#   * from absolute file (ignores <confFolder> and <extension>)
-#   * relative to where script is executed (ignores <confFolder> and <extension>)
-#   * from home/.bash-tools/<confFolder>
-#   * from framework conf/<confFolder>
+# Public: list files of dir with given extension and display it as a list one by line
 #
-# **Arguments**:
-# * $1 confFolder the directory name (not the path) to list
-# * $2 conf file to use without extension
-# * $3 the extension (sh by default)
-#
-# Returns absolute conf filename
-Profiles::getAbsoluteConfFile() {
-  local confFolder="$1"
-  local conf="$2"
-  local extension="${3-.sh}"
-  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
-    extension=".${extension}"
-  fi
-
-  testAbs() {
-    local result
-    result="$(realpath -e "$1" 2>/dev/null)"
-    # shellcheck disable=SC2181
-    if [[ "$?" = "0" && -f "${result}" ]]; then
-      echo "${result}"
-      return 0
-    fi
-    return 1
-  }
-
-  # conf is absolute file (including extension)
-  testAbs "${confFolder}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${confFolder}" && return 0
-  # conf is absolute file (including extension)
-  testAbs "${conf}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${conf}" && return 0
-
-  # relative to where script is executed (including extension)
-  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
-    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
-  fi
-  # from home/.bash-tools/<confFolder>
-  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
-
-  if [[ -n "${ROOT_DIR+xxx}" ]]; then
-    # from framework conf/<confFolder> (including extension)
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
-
-    # from framework conf/<confFolder>
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
-  fi
-
-  # file not found
-  Log::displayError "conf file '${conf}' not found"
-
-  return 1
-}
-
-# Public: list the conf files list available in bash-tools/conf/<conf> folder
-# and those overridden in ${HOME}/.bash-tools/<conf> folder
-# **Arguments**:
-# * $1 confFolder the directory name (not the path) to list
-# * $2 the extension (sh by default)
-# * $3 the indentation ('       - ' by default) can be any string compatible with sed not containing any /
-#
-# **Output**: list of files without extension/directory
+# @param {String} dir $1 the directory to list
+# @param {String} prefix $2 the profile file prefix (default: "")
+# @param {String} ext $3 the extension
+# @param {String} findOptions $4 find options, eg: -type d
+# @paramDefault {String} findOptions $4 '-type f'
+# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
+# @paramDefault {String} indentStr $5 '       - '
+# @output list of files without extension/directory
 # eg:
 #       - default.local
 #       - default.remote
 #       - localhost-root
-Profiles::getConfMergedList() {
-  local confFolder="$1"
-  local extension="${2:-sh}"
-  local indentStr="${3:-       - }"
+# @return 1 if directory does not exists
+Conf::list() {
+  local dir="$1"
+  local prefix="${2:-}"
+  local ext="${3}"
+  local findOptions="${4--type f}"
+  local indentStr="${5-       - }"
 
-  local DEFAULT_CONF_DIR="${ROOT_DIR}/conf/${confFolder}"
-  local HOME_CONF_DIR="${HOME}/.bash-tools/${confFolder}"
-
+  if [[ ! -d "${dir}" ]]; then
+    Log::displayError "Directory ${dir} does not exist"
+  fi
+  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
+    ext=".${ext}"
+  fi
   (
-    if [[ -d "${DEFAULT_CONF_DIR}" ]]; then
-      Profiles::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
-    fi
-    if [[ -d "${HOME_CONF_DIR}" ]]; then
-      Profiles::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
-    fi
-  ) | sort | uniq
-}
-
-# Public: get absolute file from name deduced using these rules
-#   * using absolute/relative <conf> file (ignores <confFolder> and <extension>
-#   * from home/.bash-tools/<confFolder>/<conf><extension> file
-#   * from framework conf/<conf><extension> file
-#
-# **Arguments**:
-# * $1 confFolder to use below bash-tools conf folder
-# * $2 conf file to use without extension
-# * $3 file extension to use (default: sh)
-#
-# Returns 1 if file not found or error during file loading
-Profiles::loadConf() {
-  local confFolder="$1"
-  local conf="$2"
-  local extension="${3:-sh}"
-
-  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
-    extension=".${extension}"
-  fi
-  # if conf is absolute
-  local confFile
-  if [[ "${conf}" == /* ]]; then
-    # file contains /, consider it as absolute filename
-    confFile="${conf}"
-  else
-    # shellcheck source=/conf/dsn/default.local.env
-    confFile="${HOME}/.bash-tools/${confFolder}/${conf}${extension}"
-    if [[ ! -f "${confFile}" ]]; then
-      confFile="${ROOT_DIR}/conf/${confFolder}/${conf}${extension}"
-    fi
-  fi
-  if [[ ! -f "${confFile}" ]]; then
-    return 1
-  fi
-  # shellcheck disable=SC1090
-  source "${confFile}"
+    # shellcheck disable=SC2086
+    cd "${dir}" &&
+      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
+      sed -E "s#^\./${prefix}##g" |
+        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
+  )
 }
 
 # lazy initialization
@@ -588,43 +621,6 @@ Log::rotate() {
   fi
 }
 
-# Public: list files of dir with given extension and display it as a list one by line
-#
-# @param {String} dir $1 the directory to list
-# @param {String} prefix $2 the profile file prefix (default: "")
-# @param {String} ext $3 the extension
-# @param {String} findOptions $4 find options, eg: -type d
-# @paramDefault {String} findOptions $4 '-type f'
-# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
-# @paramDefault {String} indentStr $5 '       - '
-# @output list of files without extension/directory
-# eg:
-#       - default.local
-#       - default.remote
-#       - localhost-root
-# @return 1 if directory does not exists
-Profiles::list() {
-  local dir="$1"
-  local prefix="${2:-}"
-  local ext="${3}"
-  local findOptions="${4--type f}"
-  local indentStr="${5-       - }"
-
-  if [[ ! -d "${dir}" ]]; then
-    Log::displayError "Directory ${dir} does not exist"
-  fi
-  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
-    ext=".${ext}"
-  fi
-  (
-    # shellcheck disable=SC2086
-    cd "${dir}" &&
-      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
-      sed -E "s#^\./${prefix}##g" |
-        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
-  )
-}
-
 # Internal: common log message
 #
 # **Arguments**:
@@ -707,6 +703,12 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
 fi
 
 BASH_FRAMEWORK_ENV_FILEPATH=${HOME}/.bash-tools/.env
+if [[ -d "${ROOT_DIR}/vendor/bash-tools-framework" ]]; then
+  FRAMEWORK_DIR="$(cd "${ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
+else
+  FRAMEWORK_DIR="${ROOT_DIR}/vendor/bash-tools-framework"
+fi
+export FRAMEWORK_DIR
 
 Assert::expectNonRootUser
 
@@ -718,9 +720,9 @@ showHelp() {
   local containers
   containers=$(docker ps --format '{{.Names}}' | sed -E 's/[^-]+-(.*)/\1/' | paste -sd "," -)
   local profilesList=""
-  Profiles::loadConf "cliProfiles" "default"
+  Conf::load "cliProfiles" "default"
 
-  profilesList="$(Profiles::getConfMergedList "cliProfiles" ".sh" || true)"
+  profilesList="$(Conf::getMergedList "cliProfiles" ".sh" || true)"
 
   cat <<EOF
 ${__HELP_TITLE}Description:${__HELP_NORMAL} easy connection to docker container
@@ -749,6 +751,9 @@ ${profilesList}
 ${__HELP_TITLE}Author:${__HELP_NORMAL}
 [François Chastanet](https://github.com/fchastanet)
 
+${__HELP_TITLE}Source file:${__HELP_NORMAL}
+https://github.com/fchastanet/bash-tools/tree/master/src/Docker/cli.sh
+
 ${__HELP_TITLE}License:${__HELP_NORMAL}
 MIT License
 
@@ -760,7 +765,7 @@ EOF
 loadDsn() {
   local dsn="$1"
   local dsnFile
-  dsnFile="$(Profiles::getAbsoluteConfFile "dsn" "${dsn}" "env")"
+  dsnFile="$(Conf::getAbsoluteFile "dsn" "${dsn}" "env")"
   Database::checkDsnFile "${dsnFile}"
   # shellcheck source=/conf/dsn/default.local.env
   # shellcheck disable=SC1091
@@ -810,10 +815,10 @@ fi
 Assert::commandExists docker "check https://docs.docker.com/engine/install/ubuntu/"
 
 # load default conf file
-Profiles::loadConf "cliProfiles" "default"
+Conf::load "cliProfiles" "default"
 # try to load config file associated to container if provided
 if [[ -n "${containerArg}" ]]; then
-  Profiles::loadConf "cliProfiles" "${containerArg}" || {
+  Conf::load "cliProfiles" "${containerArg}" || {
     # conf file not existing fallback to provided args or to default ones if not provided
     finalContainerArg="${containerArg}"
     finalUserArg=${userArg:-${finalUserArg}}
diff --git a/bin/dbQueryAllDatabases b/bin/dbQueryAllDatabases
--- a/bin/dbQueryAllDatabases
+++ b/bin/dbQueryAllDatabases
@@ -146,6 +146,97 @@ Assert::expectNonRootUser() {
   fi
 }
 
+# Public: get absolute conf file from specified conf folder deduced using these rules
+#   * from absolute file (ignores <confFolder> and <extension>)
+#   * relative to where script is executed (ignores <confFolder> and <extension>)
+#   * from home/.bash-tools/<confFolder>
+#   * from framework conf/<confFolder>
+#
+# **Arguments**:
+# * $1 confFolder the directory name (not the path) to list
+# * $2 conf file to use without extension
+# * $3 the extension (sh by default)
+#
+# Returns absolute conf filename
+Conf::getAbsoluteFile() {
+  local confFolder="$1"
+  local conf="$2"
+  local extension="${3-.sh}"
+  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
+    extension=".${extension}"
+  fi
+
+  testAbs() {
+    local result
+    result="$(realpath -e "$1" 2>/dev/null)"
+    # shellcheck disable=SC2181
+    if [[ "$?" = "0" && -f "${result}" ]]; then
+      echo "${result}"
+      return 0
+    fi
+    return 1
+  }
+
+  # conf is absolute file (including extension)
+  testAbs "${confFolder}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${confFolder}" && return 0
+  # conf is absolute file (including extension)
+  testAbs "${conf}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${conf}" && return 0
+
+  # relative to where script is executed (including extension)
+  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
+    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
+  fi
+  # from home/.bash-tools/<confFolder>
+  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
+
+  if [[ -n "${ROOT_DIR+xxx}" ]]; then
+    # from framework conf/<confFolder> (including extension)
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
+
+    # from framework conf/<confFolder>
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
+  fi
+
+  # file not found
+  Log::displayError "conf file '${conf}' not found"
+
+  return 1
+}
+
+# Public: list the conf files list available in bash-tools/conf/<conf> folder
+# and those overridden in ${HOME}/.bash-tools/<conf> folder
+# **Arguments**:
+# * $1 confFolder the directory name (not the path) to list
+# * $2 the extension (sh by default)
+# * $3 the indentation ('       - ' by default) can be any string compatible with sed not containing any /
+#
+# **Output**: list of files without extension/directory
+# eg:
+#       - default.local
+#       - default.remote
+#       - localhost-root
+Conf::getMergedList() {
+  local confFolder="$1"
+  local extension="${2:-sh}"
+  local indentStr="${3:-       - }"
+
+  local DEFAULT_CONF_DIR="${ROOT_DIR}/conf/${confFolder}"
+  local HOME_CONF_DIR="${HOME}/.bash-tools/${confFolder}"
+
+  (
+    if [[ -d "${DEFAULT_CONF_DIR}" ]]; then
+      Conf::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+    fi
+    if [[ -d "${HOME_CONF_DIR}" ]]; then
+      Conf::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+    fi
+  ) | sort | uniq
+}
+
 #  Public: lis dbs of given mysql server
 # **Output**:
 # the list of db except mysql admin ones :
@@ -169,7 +260,7 @@ Database::getUserDbList() {
 # **Arguments**:
 # * $1 - (passed by reference) database instance to create
 # * $2 - dsn profile - load the dsn.env profile
-#     absolute file is deduced using rules defined in Profiles::getAbsoluteConfFile
+#     absolute file is deduced using rules defined in Conf::getAbsoluteFile
 #
 # **Example:**
 # ```shell
@@ -192,7 +283,7 @@ Database::newInstance() {
   instanceNewInstance['DSN_FILE']=""
 
   # check dsn file
-  DSN_FILE="$(Profiles::getAbsoluteConfFile "dsn" "${dsn}" "env")" || return 1
+  DSN_FILE="$(Conf::getAbsoluteFile "dsn" "${dsn}" "env")" || return 1
   Database::checkDsnFile "${DSN_FILE}" || return 1
   instanceNewInstance['DSN_FILE']="${DSN_FILE}"
 
@@ -272,101 +363,6 @@ Log::fatal() {
   exit 1
 }
 
-# shellcheck disable=SC2034
-declare -Ag allDepsResultSeen=()
-declare -ag allDepsResult=()
-
-# Public: get absolute conf file from specified conf folder deduced using these rules
-#   * from absolute file (ignores <confFolder> and <extension>)
-#   * relative to where script is executed (ignores <confFolder> and <extension>)
-#   * from home/.bash-tools/<confFolder>
-#   * from framework conf/<confFolder>
-#
-# **Arguments**:
-# * $1 confFolder the directory name (not the path) to list
-# * $2 conf file to use without extension
-# * $3 the extension (sh by default)
-#
-# Returns absolute conf filename
-Profiles::getAbsoluteConfFile() {
-  local confFolder="$1"
-  local conf="$2"
-  local extension="${3-.sh}"
-  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
-    extension=".${extension}"
-  fi
-
-  testAbs() {
-    local result
-    result="$(realpath -e "$1" 2>/dev/null)"
-    # shellcheck disable=SC2181
-    if [[ "$?" = "0" && -f "${result}" ]]; then
-      echo "${result}"
-      return 0
-    fi
-    return 1
-  }
-
-  # conf is absolute file (including extension)
-  testAbs "${confFolder}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${confFolder}" && return 0
-  # conf is absolute file (including extension)
-  testAbs "${conf}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${conf}" && return 0
-
-  # relative to where script is executed (including extension)
-  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
-    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
-  fi
-  # from home/.bash-tools/<confFolder>
-  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
-
-  if [[ -n "${ROOT_DIR+xxx}" ]]; then
-    # from framework conf/<confFolder> (including extension)
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
-
-    # from framework conf/<confFolder>
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
-  fi
-
-  # file not found
-  Log::displayError "conf file '${conf}' not found"
-
-  return 1
-}
-
-# Public: list the conf files list available in bash-tools/conf/<conf> folder
-# and those overridden in ${HOME}/.bash-tools/<conf> folder
-# **Arguments**:
-# * $1 confFolder the directory name (not the path) to list
-# * $2 the extension (sh by default)
-# * $3 the indentation ('       - ' by default) can be any string compatible with sed not containing any /
-#
-# **Output**: list of files without extension/directory
-# eg:
-#       - default.local
-#       - default.remote
-#       - localhost-root
-Profiles::getConfMergedList() {
-  local confFolder="$1"
-  local extension="${2:-sh}"
-  local indentStr="${3:-       - }"
-
-  local DEFAULT_CONF_DIR="${ROOT_DIR}/conf/${confFolder}"
-  local HOME_CONF_DIR="${HOME}/.bash-tools/${confFolder}"
-
-  (
-    if [[ -d "${DEFAULT_CONF_DIR}" ]]; then
-      Profiles::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
-    fi
-    if [[ -d "${HOME_CONF_DIR}" ]]; then
-      Profiles::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
-    fi
-  ) | sort | uniq
-}
-
 # Check that command version is greater than expected minimal version
 # display warning if command version greater than expected minimal version
 # display error if command version less than expected minimal version and exit 1
@@ -401,6 +397,43 @@ Version::checkMinimal() {
     return 0
   }
 
+}
+
+# Public: list files of dir with given extension and display it as a list one by line
+#
+# @param {String} dir $1 the directory to list
+# @param {String} prefix $2 the profile file prefix (default: "")
+# @param {String} ext $3 the extension
+# @param {String} findOptions $4 find options, eg: -type d
+# @paramDefault {String} findOptions $4 '-type f'
+# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
+# @paramDefault {String} indentStr $5 '       - '
+# @output list of files without extension/directory
+# eg:
+#       - default.local
+#       - default.remote
+#       - localhost-root
+# @return 1 if directory does not exists
+Conf::list() {
+  local dir="$1"
+  local prefix="${2:-}"
+  local ext="${3}"
+  local findOptions="${4--type f}"
+  local indentStr="${5-       - }"
+
+  if [[ ! -d "${dir}" ]]; then
+    Log::displayError "Directory ${dir} does not exist"
+  fi
+  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
+    ext=".${ext}"
+  fi
+  (
+    # shellcheck disable=SC2086
+    cd "${dir}" &&
+      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
+      sed -E "s#^\./${prefix}##g" |
+        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
+  )
 }
 
 # Internal: check if dsn file has all the mandatory variables set
@@ -699,43 +732,6 @@ Log::rotate() {
   fi
 }
 
-# Public: list files of dir with given extension and display it as a list one by line
-#
-# @param {String} dir $1 the directory to list
-# @param {String} prefix $2 the profile file prefix (default: "")
-# @param {String} ext $3 the extension
-# @param {String} findOptions $4 find options, eg: -type d
-# @paramDefault {String} findOptions $4 '-type f'
-# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
-# @paramDefault {String} indentStr $5 '       - '
-# @output list of files without extension/directory
-# eg:
-#       - default.local
-#       - default.remote
-#       - localhost-root
-# @return 1 if directory does not exists
-Profiles::list() {
-  local dir="$1"
-  local prefix="${2:-}"
-  local ext="${3}"
-  local findOptions="${4--type f}"
-  local indentStr="${5-       - }"
-
-  if [[ ! -d "${dir}" ]]; then
-    Log::displayError "Directory ${dir} does not exist"
-  fi
-  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
-    ext=".${ext}"
-  fi
-  (
-    # shellcheck disable=SC2086
-    cd "${dir}" &&
-      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
-      sed -E "s#^\./${prefix}##g" |
-        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
-  )
-}
-
 # @param $1 version 1
 # @param $2 version 2
 # @return
@@ -856,6 +852,12 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
 fi
 
 BASH_FRAMEWORK_ENV_FILEPATH=${HOME}/.bash-tools/.env
+if [[ -d "${ROOT_DIR}/vendor/bash-tools-framework" ]]; then
+  FRAMEWORK_DIR="$(cd "${ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
+else
+  FRAMEWORK_DIR="${ROOT_DIR}/vendor/bash-tools-framework"
+fi
+export FRAMEWORK_DIR
 
 Assert::expectNonRootUser
 
@@ -872,8 +874,8 @@ declare -a PARALLEL_OPTIONS
 # Usage info
 showHelp() {
   local dsnList queriesList
-  dsnList="$(Profiles::getConfMergedList "dsn" "env")"
-  queriesList="$(Profiles::getConfMergedList "dbQueries" "sql" || true)"
+  dsnList="$(Conf::getMergedList "dsn" "env")"
+  queriesList="$(Conf::getMergedList "dbQueries" "sql" || true)"
 
   cat <<EOF
 ${__HELP_TITLE}Description:${__HELP_NORMAL} Execute a query on multiple databases in order to generate a report with tsv format, query can be parallelized on multiple databases
@@ -896,6 +898,9 @@ ${queriesList}
 
 ${__HELP_TITLE}Author:${__HELP_NORMAL}
 [François Chastanet](https://github.com/fchastanet)
+
+${__HELP_TITLE}Source file:${__HELP_NORMAL}
+https://github.com/fchastanet/bash-tools/tree/master/src/DbQueryAllDatabases/dbQueryAllDatabases.sh
 
 ${__HELP_TITLE}License:${__HELP_NORMAL}
 MIT License
@@ -973,7 +978,7 @@ fi
 declare query="${queryFile}"
 if [[ "${QUERY}" = "0" ]]; then
   declare queryAbsoluteFile
-  queryAbsoluteFile="$(Profiles::getAbsoluteConfFile "dbQueries" "${queryFile}" "sql")" ||
+  queryAbsoluteFile="$(Conf::getAbsoluteFile "dbQueries" "${queryFile}" "sql")" ||
     Log::fatal "the file ${queryFile} does not exist"
   query="$(cat "${queryAbsoluteFile}")"
   Log::displayInfo "Using query file ${queryAbsoluteFile}"
diff --git a/bin/mysql2puml b/bin/mysql2puml
--- a/bin/mysql2puml
+++ b/bin/mysql2puml
@@ -115,38 +115,6 @@ export __HELP_EXAMPLE
 export __HELP_TITLE
 export __HELP_NORMAL
 
-# Public: log level off
-export __LEVEL_OFF=0
-# Public: log level error
-export __LEVEL_ERROR=1
-# Public: log level warning
-export __LEVEL_WARNING=2
-# Public: log level info
-export __LEVEL_INFO=3
-# Public: log level success
-export __LEVEL_SUCCESS=3
-# Public: log level debug
-export __LEVEL_DEBUG=4
-
-export __LEVEL_OFF
-export __LEVEL_ERROR
-export __LEVEL_WARNING
-export __LEVEL_INFO
-export __LEVEL_SUCCESS
-export __LEVEL_DEBUG
-
-# Display message using error color (red) and exit immediately with error status 1
-# @param {String} $1 message
-Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
-  Log::logFatal "$1"
-  exit 1
-}
-
-# shellcheck disable=SC2034
-declare -Ag allDepsResultSeen=()
-declare -ag allDepsResult=()
-
 # Public: get absolute conf file from specified conf folder deduced using these rules
 #   * from absolute file (ignores <confFolder> and <extension>)
 #   * relative to where script is executed (ignores <confFolder> and <extension>)
@@ -159,7 +127,7 @@ declare -ag allDepsResult=()
 # * $3 the extension (sh by default)
 #
 # Returns absolute conf filename
-Profiles::getAbsoluteConfFile() {
+Conf::getAbsoluteFile() {
   local confFolder="$1"
   local conf="$2"
   local extension="${3-.sh}"
@@ -220,7 +188,7 @@ Profiles::getAbsoluteConfFile() {
 #       - default.local
 #       - default.remote
 #       - localhost-root
-Profiles::getConfMergedList() {
+Conf::getMergedList() {
   local confFolder="$1"
   local extension="${2:-sh}"
   local indentStr="${3:-       - }"
@@ -230,12 +198,77 @@ Profiles::getConfMergedList() {
 
   (
     if [[ -d "${DEFAULT_CONF_DIR}" ]]; then
-      Profiles::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+      Conf::list "${DEFAULT_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
     fi
     if [[ -d "${HOME_CONF_DIR}" ]]; then
-      Profiles::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
+      Conf::list "${HOME_CONF_DIR}" "" "${extension}" "-type f" "${indentStr}"
     fi
   ) | sort | uniq
+}
+
+# Public: log level off
+export __LEVEL_OFF=0
+# Public: log level error
+export __LEVEL_ERROR=1
+# Public: log level warning
+export __LEVEL_WARNING=2
+# Public: log level info
+export __LEVEL_INFO=3
+# Public: log level success
+export __LEVEL_SUCCESS=3
+# Public: log level debug
+export __LEVEL_DEBUG=4
+
+export __LEVEL_OFF
+export __LEVEL_ERROR
+export __LEVEL_WARNING
+export __LEVEL_INFO
+export __LEVEL_SUCCESS
+export __LEVEL_DEBUG
+
+# Display message using error color (red) and exit immediately with error status 1
+# @param {String} $1 message
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
+}
+
+# Public: list files of dir with given extension and display it as a list one by line
+#
+# @param {String} dir $1 the directory to list
+# @param {String} prefix $2 the profile file prefix (default: "")
+# @param {String} ext $3 the extension
+# @param {String} findOptions $4 find options, eg: -type d
+# @paramDefault {String} findOptions $4 '-type f'
+# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
+# @paramDefault {String} indentStr $5 '       - '
+# @output list of files without extension/directory
+# eg:
+#       - default.local
+#       - default.remote
+#       - localhost-root
+# @return 1 if directory does not exists
+Conf::list() {
+  local dir="$1"
+  local prefix="${2:-}"
+  local ext="${3}"
+  local findOptions="${4--type f}"
+  local indentStr="${5-       - }"
+
+  if [[ ! -d "${dir}" ]]; then
+    Log::displayError "Directory ${dir} does not exist"
+  fi
+  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
+    ext=".${ext}"
+  fi
+  (
+    # shellcheck disable=SC2086
+    cd "${dir}" &&
+      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
+      sed -E "s#^\./${prefix}##g" |
+        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
+  )
 }
 
 # lazy initialization
@@ -454,43 +487,6 @@ Log::rotate() {
   fi
 }
 
-# Public: list files of dir with given extension and display it as a list one by line
-#
-# @param {String} dir $1 the directory to list
-# @param {String} prefix $2 the profile file prefix (default: "")
-# @param {String} ext $3 the extension
-# @param {String} findOptions $4 find options, eg: -type d
-# @paramDefault {String} findOptions $4 '-type f'
-# @param {String} indentStr $5 the indentation can be any string compatible with sed not containing any /
-# @paramDefault {String} indentStr $5 '       - '
-# @output list of files without extension/directory
-# eg:
-#       - default.local
-#       - default.remote
-#       - localhost-root
-# @return 1 if directory does not exists
-Profiles::list() {
-  local dir="$1"
-  local prefix="${2:-}"
-  local ext="${3}"
-  local findOptions="${4--type f}"
-  local indentStr="${5-       - }"
-
-  if [[ ! -d "${dir}" ]]; then
-    Log::displayError "Directory ${dir} does not exist"
-  fi
-  if [[ -n "${ext}" && "${ext:0:1}" != "." ]]; then
-    ext=".${ext}"
-  fi
-  (
-    # shellcheck disable=SC2086
-    cd "${dir}" &&
-      find . -maxdepth 1 ${findOptions} -name "${prefix}*${ext}" |
-      sed -E "s#^\./${prefix}##g" |
-        sed -E "s#${ext}\$##g" | sort | sed -E "s#^#${indentStr}#"
-  )
-}
-
 # Internal: common log message
 #
 # **Arguments**:
@@ -573,6 +569,12 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
 fi
 
 BASH_FRAMEWORK_ENV_FILEPATH=${HOME}/.bash-tools/.env
+if [[ -d "${ROOT_DIR}/vendor/bash-tools-framework" ]]; then
+  FRAMEWORK_DIR="$(cd "${ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
+else
+  FRAMEWORK_DIR="${ROOT_DIR}/vendor/bash-tools-framework"
+fi
+export FRAMEWORK_DIR
 
 #default values
 SCRIPT_VERSION="0.1"
@@ -581,7 +583,7 @@ SKIN="default"
 # Usage info
 showHelp() {
   local skinList=""
-  skinList="$(Profiles::getConfMergedList "mysql2pumlSkins" ".puml")"
+  skinList="$(Conf::getMergedList "mysql2pumlSkins" ".puml")"
 
   cat <<EOF
 ${__HELP_TITLE}Description:${__HELP_NORMAL} convert mysql dump sql schema to plantuml format
@@ -605,6 +607,9 @@ ${skinList}
 
 ${__HELP_TITLE}Author:${__HELP_NORMAL}
 [François Chastanet](https://github.com/fchastanet)
+
+${__HELP_TITLE}Source file:${__HELP_NORMAL}
+https://github.com/fchastanet/bash-tools/tree/master/src/Converters/mysql2puml.sh
 
 ${__HELP_TITLE}License:${__HELP_NORMAL}
 MIT License
@@ -662,7 +667,7 @@ if (($# > 0)); then
   Log::fatal "too much arguments provided"
 fi
 
-absSkinFile="$(Profiles::getAbsoluteConfFile "mysql2pumlSkins" "${SKIN}" "puml")" ||
+absSkinFile="$(Conf::getAbsoluteFile "mysql2pumlSkins" "${SKIN}" "puml")" ||
   Log::fatal "the skin ${SKIN} does not exist"
 
 if [[ -n "${sqlFile}" ]]; then
diff --git a/conf/dbScripts/extractData b/conf/dbScripts/extractData
--- a/conf/dbScripts/extractData
+++ b/conf/dbScripts/extractData
@@ -116,7 +116,9 @@ export __HELP_TITLE
 export __HELP_NORMAL
 
 Args::defaultHelp() {
-  if ! Args::defaultHelpNoExit "$@"; then
+  local helpArg=$1
+  shift || true
+  if ! Args::defaultHelpNoExit "${helpArg}" "$@"; then
     exit 0
   fi
 }
@@ -130,12 +132,73 @@ Assert::expectNonRootUser() {
   fi
 }
 
+# Public: get absolute conf file from specified conf folder deduced using these rules
+#   * from absolute file (ignores <confFolder> and <extension>)
+#   * relative to where script is executed (ignores <confFolder> and <extension>)
+#   * from home/.bash-tools/<confFolder>
+#   * from framework conf/<confFolder>
+#
+# **Arguments**:
+# * $1 confFolder the directory name (not the path) to list
+# * $2 conf file to use without extension
+# * $3 the extension (sh by default)
+#
+# Returns absolute conf filename
+Conf::getAbsoluteFile() {
+  local confFolder="$1"
+  local conf="$2"
+  local extension="${3-.sh}"
+  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
+    extension=".${extension}"
+  fi
+
+  testAbs() {
+    local result
+    result="$(realpath -e "$1" 2>/dev/null)"
+    # shellcheck disable=SC2181
+    if [[ "$?" = "0" && -f "${result}" ]]; then
+      echo "${result}"
+      return 0
+    fi
+    return 1
+  }
+
+  # conf is absolute file (including extension)
+  testAbs "${confFolder}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${confFolder}" && return 0
+  # conf is absolute file (including extension)
+  testAbs "${conf}${extension}" && return 0
+  # conf is absolute file
+  testAbs "${conf}" && return 0
+
+  # relative to where script is executed (including extension)
+  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
+    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
+  fi
+  # from home/.bash-tools/<confFolder>
+  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
+
+  if [[ -n "${ROOT_DIR+xxx}" ]]; then
+    # from framework conf/<confFolder> (including extension)
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
+
+    # from framework conf/<confFolder>
+    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
+  fi
+
+  # file not found
+  Log::displayError "conf file '${conf}' not found"
+
+  return 1
+}
+
 # Public: create a new db instance
 #
 # **Arguments**:
 # * $1 - (passed by reference) database instance to create
 # * $2 - dsn profile - load the dsn.env profile
-#     absolute file is deduced using rules defined in Profiles::getAbsoluteConfFile
+#     absolute file is deduced using rules defined in Conf::getAbsoluteFile
 #
 # **Example:**
 # ```shell
@@ -158,7 +221,7 @@ Database::newInstance() {
   instanceNewInstance['DSN_FILE']=""
 
   # check dsn file
-  DSN_FILE="$(Profiles::getAbsoluteConfFile "dsn" "${dsn}" "env")" || return 1
+  DSN_FILE="$(Conf::getAbsoluteFile "dsn" "${dsn}" "env")" || return 1
   Database::checkDsnFile "${DSN_FILE}" || return 1
   instanceNewInstance['DSN_FILE']="${DSN_FILE}"
 
@@ -291,73 +354,8 @@ Log::fatal() {
   exit 1
 }
 
-# shellcheck disable=SC2034
-declare -Ag allDepsResultSeen=()
-declare -ag allDepsResult=()
-
-# Public: get absolute conf file from specified conf folder deduced using these rules
-#   * from absolute file (ignores <confFolder> and <extension>)
-#   * relative to where script is executed (ignores <confFolder> and <extension>)
-#   * from home/.bash-tools/<confFolder>
-#   * from framework conf/<confFolder>
-#
-# **Arguments**:
-# * $1 confFolder the directory name (not the path) to list
-# * $2 conf file to use without extension
-# * $3 the extension (sh by default)
-#
-# Returns absolute conf filename
-Profiles::getAbsoluteConfFile() {
-  local confFolder="$1"
-  local conf="$2"
-  local extension="${3-.sh}"
-  if [[ -n "${extension}" && "${extension:0:1}" != "." ]]; then
-    extension=".${extension}"
-  fi
-
-  testAbs() {
-    local result
-    result="$(realpath -e "$1" 2>/dev/null)"
-    # shellcheck disable=SC2181
-    if [[ "$?" = "0" && -f "${result}" ]]; then
-      echo "${result}"
-      return 0
-    fi
-    return 1
-  }
-
-  # conf is absolute file (including extension)
-  testAbs "${confFolder}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${confFolder}" && return 0
-  # conf is absolute file (including extension)
-  testAbs "${conf}${extension}" && return 0
-  # conf is absolute file
-  testAbs "${conf}" && return 0
-
-  # relative to where script is executed (including extension)
-  if [[ -n "${CURRENT_DIR+xxx}" ]]; then
-    testAbs "$(File::concatenatePath "${CURRENT_DIR}" "${confFolder}")/${conf}${extension}" && return 0
-  fi
-  # from home/.bash-tools/<confFolder>
-  testAbs "$(File::concatenatePath "${HOME}/.bash-tools" "${confFolder}")/${conf}${extension}" && return 0
-
-  if [[ -n "${ROOT_DIR+xxx}" ]]; then
-    # from framework conf/<confFolder> (including extension)
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}${extension}" && return 0
-
-    # from framework conf/<confFolder>
-    testAbs "$(File::concatenatePath "${ROOT_DIR}/conf" "${confFolder}")/${conf}" && return 0
-  fi
-
-  # file not found
-  Log::displayError "conf file '${conf}' not found"
-
-  return 1
-}
-
 Args::defaultHelpNoExit() {
-  local helpArg="$1"
+  local helpArg=$1
   shift || true
   # shellcheck disable=SC2034
   local args
@@ -367,7 +365,11 @@ Args::defaultHelpNoExit() {
   while true; do
     case $1 in
       -h | --help)
-        Args::showHelp "${helpArg}"
+        if [[ "$(type -t "${helpArg}")" = "function" ]]; then
+          "${helpArg}" "$@"
+        else
+          Args::showHelp "${helpArg}"
+        fi
         return 1
         ;;
       --)
@@ -723,6 +725,12 @@ if ((BASH_FRAMEWORK_LOG_LEVEL > __LEVEL_OFF)); then
 fi
 
 BASH_FRAMEWORK_ENV_FILEPATH=${HOME}/.bash-tools/.env
+if [[ -d "${ROOT_DIR}/vendor/bash-tools-framework" ]]; then
+  FRAMEWORK_DIR="$(cd "${ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
+else
+  FRAMEWORK_DIR="${ROOT_DIR}/vendor/bash-tools-framework"
+fi
+export FRAMEWORK_DIR
 
 ############################################################
 # INTERNAL USE ONLY
@@ -762,6 +770,9 @@ be used by bin/dbScriptAllDatabases
 ${__HELP_TITLE}Author:${__HELP_NORMAL}
 [François Chastanet](https://github.com/fchastanet)
 
+${__HELP_TITLE}Source file:${__HELP_NORMAL}
+https://github.com/fchastanet/bash-tools/tree/master/src/DbScriptAllDatabases/extractData.sh
+
 ${__HELP_TITLE}License:${__HELP_NORMAL}
 MIT License
 
@@ -779,7 +790,7 @@ fi
 declare query="${scriptParameters[0]}"
 declare queryName="customQuery"
 declare queryFile="${query}"
-queryFile="$(Profiles::getAbsoluteConfFile "dbQueries" "${queryFile}" "sql" 2>/dev/null || echo "")"
+queryFile="$(Conf::getAbsoluteFile "dbQueries" "${queryFile}" "sql" 2>/dev/null || echo "")"
 if [[ -n "${queryFile}" ]]; then
   queryName="$(basename "${queryFile%.*}")"
   query="$(cat "${queryFile}")"
