fixed UT flakiness
- using Bash::handlePipelineFailure
- removed usage of Embeded binaries in dbScriptAllDatabases and dbQueryAllDatabases

diff --git a/bin/dbImport b/bin/dbImport
--- a/bin/dbImport
+++ b/bin/dbImport
@@ -264,6 +264,36 @@ Assert::commandExists() {
   return 0
 }
 
+# @description ignore exit code 141 from simple command pipes
+# @example use with:
+#   local resultingStatus=0
+#   local -a originalPipeStatus=()
+#   cmd1 | cmd2 || Bash::handlePipelineFailure resultingStatus originalPipeStatus || true
+#   [[ "${resultingStatus}" = "0" ]]
+# @arg $1 resultingStatusCode:&int (passed by reference) (optional) resulting status code
+# @arg $2 originalStatus:int[] (passed by reference) (optional) copy of original PIPESTATUS array
+# @env PIPESTATUS assuming that this function is called like in the example provided
+# @see https://unix.stackexchange.com/a/709880/582856
+Bash::handlePipelineFailure() {
+  local -a pipeStatusBackup=("${PIPESTATUS[@]}")
+  local -n handlePipelineFailure_resultingStatusCode=$1
+  local -n handlePipelineFailure_originalStatus=$2
+  # shellcheck disable=SC2034
+  handlePipelineFailure_originalStatus=("${pipeStatusBackup[@]}")
+  handlePipelineFailure_resultingStatusCode=0
+  local statusCode
+  for statusCode in "${pipeStatusBackup[@]}"; do
+    if ((statusCode == 141)); then
+      return 0
+    elif ((statusCode > 0)); then
+      # shellcheck disable=SC2034
+      handlePipelineFailure_resultingStatusCode="${statusCode}"
+      break
+    fi
+  done
+  return "${handlePipelineFailure_resultingStatusCode}"
+}
+
 # @description get absolute conf file from specified conf folder deduced using these rules
 #   * from absolute file (ignores <confFolder> and <extension>)
 #   * relative to where script is executed (ignores <confFolder> and <extension>)
@@ -874,36 +904,6 @@ Assert::tty() {
     return 0
   fi
   [[ -t 1 || -t 2 ]]
-}
-
-# @description ignore exit code 141 from simple command pipes
-# @example use with:
-#   local resultingStatus=0
-#   local -a originalPipeStatus=()
-#   cmd1 | cmd2 || Bash::handlePipelineFailure resultingStatus originalPipeStatus || true
-#   [[ "${resultingStatus}" = "0" ]]
-# @arg $1 resultingStatusCode:&int (passed by reference) (optional) resulting status code
-# @arg $2 originalStatus:int[] (passed by reference) (optional) copy of original PIPESTATUS array
-# @env PIPESTATUS assuming that this function is called like in the example provided
-# @see https://unix.stackexchange.com/a/709880/582856
-Bash::handlePipelineFailure() {
-  local -a pipeStatusBackup=("${PIPESTATUS[@]}")
-  local -n handlePipelineFailure_resultingStatusCode=$1
-  local -n handlePipelineFailure_originalStatus=$2
-  # shellcheck disable=SC2034
-  handlePipelineFailure_originalStatus=("${pipeStatusBackup[@]}")
-  handlePipelineFailure_resultingStatusCode=0
-  local statusCode
-  for statusCode in "${pipeStatusBackup[@]}"; do
-    if ((statusCode == 141)); then
-      return 0
-    elif ((statusCode > 0)); then
-      # shellcheck disable=SC2034
-      handlePipelineFailure_resultingStatusCode="${statusCode}"
-      break
-    fi
-  done
-  return "${handlePipelineFailure_resultingStatusCode}"
 }
 
 # @description list files of dir with given extension and display it as a list one by line
@@ -2396,9 +2396,13 @@ run() {
       Log::displayInfo "avoid to create db structure"
     else
       Log::displayInfo "create db structure from ${remoteDbStructureDumpTempFile}"
+      # shellcheck disable=SC2034
+      local status=0
+      # shellcheck disable=SC2034
+      local -a pipeStatus=()
       time (
         pv "${remoteDbStructureDumpTempFile}" | zcat |
-          Database::query dbTargetDatabase "" "${targetDbName}"
+          Database::query dbTargetDatabase "" "${targetDbName}" || Bash::handlePipelineFailure status pipeStatus
       )
     fi
   fi
diff --git a/bin/dbImportStream b/bin/dbImportStream
--- a/bin/dbImportStream
+++ b/bin/dbImportStream
@@ -264,6 +264,36 @@ Assert::commandExists() {
   return 0
 }
 
+# @description ignore exit code 141 from simple command pipes
+# @example use with:
+#   local resultingStatus=0
+#   local -a originalPipeStatus=()
+#   cmd1 | cmd2 || Bash::handlePipelineFailure resultingStatus originalPipeStatus || true
+#   [[ "${resultingStatus}" = "0" ]]
+# @arg $1 resultingStatusCode:&int (passed by reference) (optional) resulting status code
+# @arg $2 originalStatus:int[] (passed by reference) (optional) copy of original PIPESTATUS array
+# @env PIPESTATUS assuming that this function is called like in the example provided
+# @see https://unix.stackexchange.com/a/709880/582856
+Bash::handlePipelineFailure() {
+  local -a pipeStatusBackup=("${PIPESTATUS[@]}")
+  local -n handlePipelineFailure_resultingStatusCode=$1
+  local -n handlePipelineFailure_originalStatus=$2
+  # shellcheck disable=SC2034
+  handlePipelineFailure_originalStatus=("${pipeStatusBackup[@]}")
+  handlePipelineFailure_resultingStatusCode=0
+  local statusCode
+  for statusCode in "${pipeStatusBackup[@]}"; do
+    if ((statusCode == 141)); then
+      return 0
+    elif ((statusCode > 0)); then
+      # shellcheck disable=SC2034
+      handlePipelineFailure_resultingStatusCode="${statusCode}"
+      break
+    fi
+  done
+  return "${handlePipelineFailure_resultingStatusCode}"
+}
+
 # @description get absolute conf file from specified conf folder deduced using these rules
 #   * from absolute file (ignores <confFolder> and <extension>)
 #   * relative to where script is executed (ignores <confFolder> and <extension>)
@@ -784,36 +814,6 @@ Assert::tty() {
     return 0
   fi
   [[ -t 1 || -t 2 ]]
-}
-
-# @description ignore exit code 141 from simple command pipes
-# @example use with:
-#   local resultingStatus=0
-#   local -a originalPipeStatus=()
-#   cmd1 | cmd2 || Bash::handlePipelineFailure resultingStatus originalPipeStatus || true
-#   [[ "${resultingStatus}" = "0" ]]
-# @arg $1 resultingStatusCode:&int (passed by reference) (optional) resulting status code
-# @arg $2 originalStatus:int[] (passed by reference) (optional) copy of original PIPESTATUS array
-# @env PIPESTATUS assuming that this function is called like in the example provided
-# @see https://unix.stackexchange.com/a/709880/582856
-Bash::handlePipelineFailure() {
-  local -a pipeStatusBackup=("${PIPESTATUS[@]}")
-  local -n handlePipelineFailure_resultingStatusCode=$1
-  local -n handlePipelineFailure_originalStatus=$2
-  # shellcheck disable=SC2034
-  handlePipelineFailure_originalStatus=("${pipeStatusBackup[@]}")
-  handlePipelineFailure_resultingStatusCode=0
-  local statusCode
-  for statusCode in "${pipeStatusBackup[@]}"; do
-    if ((statusCode == 141)); then
-      return 0
-    elif ((statusCode > 0)); then
-      # shellcheck disable=SC2034
-      handlePipelineFailure_resultingStatusCode="${statusCode}"
-      break
-    fi
-  done
-  return "${handlePipelineFailure_resultingStatusCode}"
 }
 
 # @description list files of dir with given extension and display it as a list one by line
@@ -2065,7 +2065,7 @@ run() {
   Version::checkMinimal "gawk" "--version" "5.0.1"
 
   # create db instances
-  declare -Agx dbTargetInstance
+  local -Agx dbTargetInstance
 
   Database::newInstance dbTargetInstance "${optionTargetDsn}"
   Database::setQueryOptions dbTargetInstance "${dbTargetInstance[QUERY_OPTIONS]} --connect-timeout=5"
@@ -2074,7 +2074,11 @@ run() {
   initializeDefaultTargetMysqlOptions dbTargetInstance "${argTargetDbName}"
 
   # TODO character set should be retrieved from dump files if possible
-  declare remoteCharacterSet="${optionCharacterSet:-${defaultRemoteCharacterSet}}"
+  local remoteCharacterSet="${optionCharacterSet:-${defaultRemoteCharacterSet}}"
+
+  local status=0
+  # shellcheck disable=SC2034
+  local -a pipeStatus=()
 
   # shellcheck disable=2086
   (
@@ -2083,19 +2087,19 @@ run() {
     elif [[ "${argDumpFile}" =~ \.gz$ ]]; then
       zcat "${argDumpFile}"
     fi
-    # zcat will continue to write to stdout whereas awk has finished if table has been found
-    # we detect this case because zcat will return code 141 because pipe closed
-    status=$?
-    if [[ "${status}" -eq "141" ]]; then true; else exit "${status}"; fi
   ) |
     awk \
       -v PROFILE_COMMAND="${profileCommandFile}" \
       -v CHARACTER_SET="${remoteCharacterSet}" \
       --source "${awkScript}" \
-      - | mysql \
-    "--defaults-extra-file=${dbTargetInstance['AUTH_FILE']}" \
-    ${dbTargetInstance['DB_IMPORT_OPTIONS']} \
-    "${argTargetDbName}" || exit $?
+      - |
+    mysql \
+      "--defaults-extra-file=${dbTargetInstance['AUTH_FILE']}" \
+      ${dbTargetInstance['DB_IMPORT_OPTIONS']} \
+      "${argTargetDbName}" ||
+    # zcat will continue to write to stdout whereas awk has finished if table has been found
+    # we detect this case because zcat will return code 141 because pipe closed
+    Bash::handlePipelineFailure status pipeStatus
 }
 
 if [[ "${BASH_FRAMEWORK_QUIET_MODE:-0}" = "1" ]]; then
