commit as is - added dsn support

diff --git a/bin/dbImport b/bin/dbImport
--- a/bin/dbImport
+++ b/bin/dbImport
@@ -29,6 +29,8 @@ REMOTE_DB=""
 LOCAL_DB=""
 COLLATION_NAME=""
 CHARACTER_SET=""
+FROM_DSN=""
+TARGET_DSN="default.local"
 TIMEFORMAT='time spent : %3R'
 
 # check dependencies
@@ -41,33 +43,45 @@ showHelp() {
     local profilesList=""
     local homeProfilesList=""
 
-    profilesList=$(cd "${PROFILES_DIR}" && find . -type f -name \*.sh -printf '%P\n' | sed 's/\.sh$//g' | paste -sd "," - | sed -e 's/,/, /g')
+    profilesList=$(cd "${PROFILES_DIR}" && find . -type f -name \*.sh | sed 's#^./##g' | sed 's/\.sh$//g' | paste -sd "," - | sed -e 's/,/, /g')
 
     if [[ -d "${HOME_PROFILES_DIR}" ]]; then
-        homeProfilesList=$(cd "${HOME_PROFILES_DIR}" && find . -type f -name \*.sh -printf '%P\n' | sed 's/\.sh$//g' | paste -sd "," - | sed -e 's/,/, /g')
+        homeProfilesList=$(cd "${HOME_PROFILES_DIR}" && find . -type f -name \*.sh | sed 's#^./##g' | sed 's/\.sh$//g' | paste -sd "," - | sed -e 's/,/, /g')
     fi
+
+
 cat << EOF
-Description: Import remote db into local db
+Description: Import source db into target db
 
 Usage: ${SCRIPT_NAME} --help prints this help and exits
-Usage: ${SCRIPT_NAME} <remoteDbName> [<localDbName>] [-f|--force] 
+Usage: ${SCRIPT_NAME} <fromDbName> [<targetDbName>] 
+                        [--force] 
                         [-d|--download-dump] [-a|--from-aws]
                         [-s|--skip-schema] [-p|--profile profileName] 
                         [-o|--collation-name utf8_general_ci] [-c|--character-set utf8]
+                        [-t|--target-dsn dsn] [-f|--from-dsn dsn]
 
     <localDbName> : use remote db name if not provided
-    -f|--force If local db exists, it will overwrite it
-    -d|--download-dump force remote db dump (default: use already downloaded dump in ${DB_IMPORT_DUMP_DIR} if available)
-    -a|--from-aws db dump will be downloaded from s3 instead of using remote db, 
-        remoteDBName will represent the name of the file
-        profile will be calculated against the dump itself
-    -s|--skip-schema avoid to import the schema
-    -o|--collation-name change the collation name used during database creation (default value: collation name used by remote db)
-    -c|--character-set change the character set used during database creation (default value: character set used by remote db)
-    -p|--profile profileName the name of the profile to use in order to include or exclude tables
+    -f|--force                  If local db exists, it will overwrite it
+    -d|--download-dump          force remote db dump (default: use already downloaded dump 
+        in ${DB_IMPORT_DUMP_DIR} if available)
+    -s|--skip-schema            avoid to import the schema
+    -o|--collation-name         change the collation name used during database creation 
+        (default value: collation name used by remote db)
+    -c|--character-set          change the character set used during database creation 
+        (default value: character set used by remote db)
+    -p|--profile profileName    the name of the profile to use in order to include or exclude tables
         (if not specified ${HOME_PROFILES_DIR}/default.sh  is used if exists otherwise ${PROFILES_DIR}/default.sh)
         list of available home profiles (${HOME_PROFILES_DIR}): ${homeProfilesList}
         list of available profiles : ${profilesList}
+    -t|--target-dsn dsn         dsn to use for target database 
+    -f|--from-dsn dsn           dsn to use for source database
+        this option is incompatible with -a|--from-aws option
+    -a|--from-aws               db dump will be downloaded from s3 instead of using remote db, 
+        remoteDBName will represent the name of the file
+        profile will be calculated against the dump itself
+        this option is incompatible with -f|--from-dsn option
+
 
     local DB connection   : ${MYSQL_ROOT_USER}:Hidden@${MYSQL_HOSTNAME}:${MYSQL_PORT}
     remote DB connection  : ${REMOTE_MYSQL_USER}:Hidden@${REMOTE_MYSQL_HOSTNAME}:${REMOTE_MYSQL_PORT}
@@ -80,7 +94,7 @@ EOF
 # -o is for short options like -h
 # -l is for long options with double dash like --help
 # the comma separates different long options
-options=$(getopt -l help,force,from-aws,download-dump,skip-schema,profile:,collation-name:,character-set: -o ahfdsp:c:o: -- "$@" 2> /dev/null) || {
+options=$(getopt -l help,force,target-dsn:,from-dsn:,from-aws,download-dump,skip-schema,profile:,collation-name:,character-set: -o aht:f:dsp:c:o: -- "$@" 2> /dev/null) || {
     Log::displayError "invalid options specified"
     showHelp
     exit 1
@@ -94,7 +108,7 @@ case $1 in
     showHelp
     exit 0
     ;;
--f|--force)
+--force)
     Log::displayInfo "If local db exists, it will overwrite it"
     FORCE=1
     ;;
@@ -105,6 +119,14 @@ case $1 in
     FROM_AWS="1"
     # structure is included in s3 file
     SKIP_SCHEMA="1"
+    ;;
+-t|--target-dsn)
+    shift
+    TARGET_DSN="$1"
+    ;;
+-f|--from-dsn)
+    shift
+    FROM_DSN="${1:-default.remote}"
     ;;
 -s|--skip-schema)
     SKIP_SCHEMA="1"
@@ -158,20 +180,19 @@ if [[ -z "${LOCAL_DB}" ]]; then
     LOCAL_DB=${REMOTE_DB}
 fi
 
-#check that remote db env variables are set
-if [[ -z "${REMOTE_MYSQL_HOSTNAME}" || -z "${REMOTE_MYSQL_PORT}" || -z "${REMOTE_MYSQL_USER}" || -z "${REMOTE_MYSQL_PASSWORD}" ]]; then
-    Log::displayError "missing remote mysql parameters, please provide a value in .env file"
+# check s3 parameter
+if [[ "${FROM_AWS}" = "1" && -n "${FROM_DSN}" ]]; then
+    Log::displayError "you cannot use from-dsn and from-aws at the same time"
     exit 1
 fi
-
-if [[ "${MYSQL_HOSTNAME}" = "localhost" ]]; then
-    Log::displayWarning "check that MYSQL_HOSTNAME should not be 127.0.0.1 instead of localhost"
-fi
-
-# check s3 parameter
 if [[ "${FROM_AWS}" = "1" && -z "${S3_BASE_URL}" ]]; then
     Log::displayError "missing S3_BASE_URL, please provide a value in .env file"
     exit 1
+fi
+
+# default value for FROM_DSN if from-aws not set
+if [[ "${FROM_AWS}" = "0" && -z "${FROM_DSN}" ]]; then
+    FROM_DSN="default.remote"
 fi
 
 # load the profile
@@ -191,15 +212,18 @@ else
 fi
 
 # create db instances
-declare -Agx dbRemoteInstance dbLocalInstance
-Database::newInstance dbLocalInstance "${MYSQL_HOSTNAME}" "${MYSQL_PORT}" "${MYSQL_ROOT_USER}" "${MYSQL_ROOT_PASSWORD}"
-Database::setOptions dbLocalInstance "${MYSQL_OPTIONS} --connect-timeout=5"
-Database::newInstance dbRemoteInstance "${REMOTE_MYSQL_HOSTNAME}" "${REMOTE_MYSQL_PORT}" "${REMOTE_MYSQL_USER}" "${REMOTE_MYSQL_PASSWORD}"
-Database::setOptions dbRemoteInstance "${MYSQL_OPTIONS} --connect-timeout=5"
+declare -Agx dbFromInstance dbTargetDatabase
+
+Database::newInstance dbTargetDatabase "${TARGET_DSN}"
+Database::setOptions dbTargetDatabase "${MYSQL_OPTIONS} --connect-timeout=5"
+if [[ "${FROM_AWS}" = "0" ]; then
+    Database::newInstance dbFromInstance "${FROM_DSN}"
+    Database::setOptions dbFromInstance "${MYSQL_OPTIONS} --connect-timeout=5"
+fi
 
 # check if local db exists
 LOCAL_DB_EXISTS=0
-Database::ifDbExists dbLocalInstance "${LOCAL_DB}" && {
+Database::ifDbExists dbTargetDatabase "${LOCAL_DB}" && {
     Log::displayInfo "Local Database ${LOCAL_DB} already exists !"
     if [[ "${FORCE}" = "0" ]]; then
         Log::displayError "use --force to drop it"
@@ -275,26 +299,26 @@ if [[ "${DOWNLOAD_DUMP}" = "1" ]]; then
     else
         # get remote db collation name
         if [[ -z "${COLLATION_NAME}" ]]; then
-            COLLATION_NAME=$(Database::query dbRemoteInstance \
+            COLLATION_NAME=$(Database::query dbFromInstance \
                 "SELECT default_collation_name FROM information_schema.SCHEMATA WHERE schema_name = \"${REMOTE_DB}\";" "information_schema")
         fi
 
         # get remote db character set
         if [[ -z "${CHARACTER_SET}" ]]; then
-            CHARACTER_SET=$(Database::query dbRemoteInstance \
+            CHARACTER_SET=$(Database::query dbFromInstance \
                 "SELECT default_character_set_name FROM information_schema.SCHEMATA WHERE schema_name = \"${REMOTE_DB}\";" "information_schema")
         fi
 
         DUMP_HEADER=$(printf "${DUMP_HEADER}\nSET names '${CHARACTER_SET}';\n")
 
         # check if remote db exists
-        Database::ifDbExists dbRemoteInstance "${REMOTE_DB}" || {
+        Database::ifDbExists dbFromInstance "${REMOTE_DB}" || {
             Log::displayError "Remote Database ${REMOTE_DB} does not exist"
             exit 1
         }
 
         # calculate remote db dump size
-        FULL_LIST_TABLES="$(Database::query dbRemoteInstance "show tables" "${REMOTE_DB}")"
+        FULL_LIST_TABLES="$(Database::query dbFromInstance "show tables" "${REMOTE_DB}")"
         LIST_TABLES="$(echo "${FULL_LIST_TABLES}" | ${PROFILE_COMMAND})"
         readarray -t LIST_TABLES_ARRAY <<< ${LIST_TABLES}
         IFS=$'\n' eval 'LIST_TABLES_ARRAY=(${LIST_TABLES})'
@@ -304,7 +328,7 @@ if [[ "${DOWNLOAD_DUMP}" = "1" ]]; then
         DUMP_SIZE_QUERY="SELECT ROUND(SUM(data_length + index_length) / 1024 / 1024, 0) AS size FROM information_schema.TABLES WHERE table_schema=\"${REMOTE_DB}\""
         DUMP_SIZE_QUERY+=" AND table_name IN(${LIST_TABLES_DUMP} 'dummy') "
         DUMP_SIZE_QUERY+=" GROUP BY table_schema"
-        REMOTE_DB_DUMP_SIZE=$(echo "${DUMP_SIZE_QUERY}" | Database::query dbRemoteInstance )
+        REMOTE_DB_DUMP_SIZE=$(echo "${DUMP_SIZE_QUERY}" | Database::query dbFromInstance )
         if [[ -z "${REMOTE_DB_DUMP_SIZE}" ]]; then
             # could occur with the none profile
             REMOTE_DB_DUMP_SIZE="0"
@@ -314,13 +338,13 @@ if [[ "${DOWNLOAD_DUMP}" = "1" ]]; then
         Log::displayInfo "Dump the database $REMOTE_DB (Size:${REMOTE_DB_DUMP_SIZE}MB) ...";
         echo "${DUMP_HEADER}" > "${REMOTE_DB_DUMP_TEMP_FILE}"
         DUMP_SIZE_PV_ESTIMATION=$(awk "BEGIN {printf \"%.0f\",${REMOTE_DB_DUMP_SIZE}/1.5}")
-        time Database::dump dbRemoteInstance "${REMOTE_DB}" "${LIST_TABLES_DUMP//[,]/ }" --no-create-info --skip-add-drop-table --single-transaction=TRUE | \
+        time Database::dump dbFromInstance "${REMOTE_DB}" "${LIST_TABLES_DUMP//[,]/ }" --no-create-info --skip-add-drop-table --single-transaction=TRUE | \
             pv --progress --size ${DUMP_SIZE_PV_ESTIMATION}m >> "${REMOTE_DB_DUMP_TEMP_FILE}"
         echo "${DUMP_FOOTER}" >> "${REMOTE_DB_DUMP_TEMP_FILE}"
 
         Log::displayInfo "Dump structure of the database ${REMOTE_DB} ...";
         echo "${DUMP_HEADER}" > "${REMOTE_DB_STRUCTURE_DUMP_TEMP_FILE}"
-        time Database::dump dbRemoteInstance "${REMOTE_DB}" "" --no-data --skip-add-drop-table --single-transaction=TRUE \
+        time Database::dump dbFromInstance "${REMOTE_DB}" "" --no-data --skip-add-drop-table --single-transaction=TRUE \
             >> "${REMOTE_DB_STRUCTURE_DUMP_TEMP_FILE}"
         echo "${DUMP_FOOTER}" >> "${REMOTE_DB_STRUCTURE_DUMP_TEMP_FILE}"
     fi
@@ -333,11 +357,11 @@ fi
 # drop local db
 if [[ "${LOCAL_DB_EXISTS}" = "1" ]]; then
     Log::displayInfo "drop local database ${LOCAL_DB}";
-    Database::query dbLocalInstance "DROP DATABASE IF EXISTS ${LOCAL_DB}"
+    Database::query dbTargetDatabase "DROP DATABASE IF EXISTS ${LOCAL_DB}"
 fi
 
 Log::displayInfo "create local database ${LOCAL_DB}";
-Database::query dbLocalInstance "CREATE DATABASE ${LOCAL_DB}/*!40100 COLLATE \"${COLLATION_NAME}\" */"
+Database::query dbTargetDatabase "CREATE DATABASE ${LOCAL_DB}/*!40100 COLLATE \"${COLLATION_NAME}\" */"
 
 if [[ "${FROM_AWS}" = "1" ]]; then
     "${CURRENT_DIR}/dbImportStream" \
@@ -353,14 +377,14 @@ else
         Log::displayInfo "create db structure from ${REMOTE_DB_STRUCTURE_DUMP_TEMP_FILE}";
         time ( \
             pv "${REMOTE_DB_STRUCTURE_DUMP_TEMP_FILE}" | \
-                Database::query dbLocalInstance "" "${LOCAL_DB}"
+                Database::query dbTargetDatabase "" "${LOCAL_DB}"
         )
     fi
 
     Log::displayInfo "import remote to local from file ${REMOTE_DB_DUMP_TEMP_FILE}"
     time ( \
         pv "${REMOTE_DB_DUMP_TEMP_FILE}" | \
-            Database::query dbLocalInstance "" "${LOCAL_DB}"
+            Database::query dbTargetDatabase "" "${LOCAL_DB}"
     )
 fi
 
