Refactoring to remove duplicated code
- move conf/.env to conf/defaultEnv/.env in order to
  be able to include the .env file using gtpl
  it avoids usage of @embed feature removing the
  need of tar command in BashTools::Conf::requireLoad
- added
  src/_binaries/commandDefinitions/optionsDefault.yaml
  to set default binary options for all the binaries
  beforeParseCallback calling
  defaultBeforeParseCallback
- avoid duplicated code by using the new
  fromDsnOptionLongDescription function
- reformatted long description for all Database's
  binaries
- better optionProfile default value management
  that can be default or empty depending the case
- added
  src/_binaries/commandDefinitions/optionsTables.sh
  src/_binaries/commandDefinitions/optionsRatio.yaml
  in order to correctly order the options in help
- move requirements to beforeParseCallback
- recompiled all binaries to remove deprecated
  option --env-file

diff --git a/bin/dbQueryAllDatabases b/bin/dbQueryAllDatabases
--- a/bin/dbQueryAllDatabases
+++ b/bin/dbQueryAllDatabases
@@ -338,18 +338,79 @@ Bash::handlePipelineFailure() {
 }
 
 
+read -r -d '\0' bashToolsDefaultConfigTemplate <<-EOM || true
+#
+# shellcheck disable=SC2034
+
+# Default settings
+# you can override these settings by creating ${HOME}/.bash-tools/.env file
+
+###
+### DISPLAY Level
+### minimum level of the messages that will be displayed on screen
+###
+### 0: NO LOG
+### 1: ERROR
+### 2: WARNING
+### 3: INFO
+### 4: DEBUG
+###
+BASH_FRAMEWORK_DISPLAY_LEVEL=${BASH_FRAMEWORK_DISPLAY_LEVEL:-3}
+
+###
+### DISPLAY duration
+### 0: no duration is displayed on the messages
+### 1: duration between previous message and current is displayed
+### with the message
+###
+DISPLAY_DURATION=${DISPLAY_DURATION:0}
+
+###
+### Log to file
+###
+### all log messages will be redirected to log file specified
+### this same path will be used inside and outside of the container
+###
+BASH_FRAMEWORK_LOG_FILE=${BASH_FRAMEWORK_LOG_FILE:-${FRAMEWORK_ROOT_DIR}/logs/bash.log}
+
+###
+### LOG Level
+### minimum level of the messages that will be logged into LOG_FILE
+###
+### 0: NO LOG
+### 1: ERROR
+### 2: WARNING
+### 3: INFO
+### 4: DEBUG
+###
+BASH_FRAMEWORK_LOG_LEVEL=${BASH_FRAMEWORK_LOG_LEVEL:-0}
+
+# absolute directory containing db import sql dumps
+DB_IMPORT_DUMP_DIR=${DB_IMPORT_DUMP_DIR:-${HOME}/.bash-tools/dbImportDumps}
+
+# garbage collect all files for which modification is greater than eg: 30 days (+30)
+# each time an existing file is used by dbImport/dbImportTable
+# the file modification time is set to now
+DB_IMPORT_GARBAGE_COLLECT_DAYS=${DB_IMPORT_GARBAGE_COLLECT_DAYS:-+30}
+
+# absolute directory containing dbScripts used by dbScriptAllDatabases
+SCRIPTS_FOLDER=${SCRIPTS_FOLDER:-${HOME}/.bash-tools/conf/dbScripts}
+
+# -----------------------------------------------------
+# AWS Parameters
+# -----------------------------------------------------
+S3_BASE_URL=${S3_BASE_URL:-}
+
+# -----------------------------------------------------
+# Postman Parameters
+# -----------------------------------------------------
+POSTMAN_API_KEY=
+EOM
+
 # @description loads ~/.bash-tools/.env if available
 # if not creates it from a default template
 # else check if new options need to be added
 BashTools::Conf::requireLoad() {
-Linux::requireTarCommand
-Compiler::Embed::extractFileFromBase64 \
-  "${PERSISTENT_TMPDIR:-/tmp}/db87222729e0f1ed9c597a486a61a08c/bashToolsDefaultConfigTemplate" \
-  "IyEvdXNyL2Jpbi9lbnYgYmFzaAojIHNoZWxsY2hlY2sgZGlzYWJsZT1TQzIwMzQKCiMgRGVmYXVsdCBzZXR0aW5ncwojIHlvdSBjYW4gb3ZlcnJpZGUgdGhlc2Ugc2V0dGluZ3MgYnkgY3JlYXRpbmcgJHtIT01FfS8uYmFzaC10b29scy8uZW52IGZpbGUKCiMjIwojIyMgRElTUExBWSBMZXZlbAojIyMgbWluaW11bSBsZXZlbCBvZiB0aGUgbWVzc2FnZXMgdGhhdCB3aWxsIGJlIGRpc3BsYXllZCBvbiBzY3JlZW4KIyMjCiMjIyAwOiBOTyBMT0cKIyMjIDE6IEVSUk9SCiMjIyAyOiBXQVJOSU5HCiMjIyAzOiBJTkZPCiMjIyA0OiBERUJVRwojIyMKQkFTSF9GUkFNRVdPUktfRElTUExBWV9MRVZFTD0ke0JBU0hfRlJBTUVXT1JLX0RJU1BMQVlfTEVWRUw6LTN9CgojIyMKIyMjIERJU1BMQVkgZHVyYXRpb24KIyMjIDA6IG5vIGR1cmF0aW9uIGlzIGRpc3BsYXllZCBvbiB0aGUgbWVzc2FnZXMKIyMjIDE6IGR1cmF0aW9uIGJldHdlZW4gcHJldmlvdXMgbWVzc2FnZSBhbmQgY3VycmVudCBpcyBkaXNwbGF5ZWQKIyMjIHdpdGggdGhlIG1lc3NhZ2UKIyMjCkRJU1BMQVlfRFVSQVRJT049JHtESVNQTEFZX0RVUkFUSU9OOjB9CgojIyMKIyMjIExvZyB0byBmaWxlCiMjIwojIyMgYWxsIGxvZyBtZXNzYWdlcyB3aWxsIGJlIHJlZGlyZWN0ZWQgdG8gbG9nIGZpbGUgc3BlY2lmaWVkCiMjIyB0aGlzIHNhbWUgcGF0aCB3aWxsIGJlIHVzZWQgaW5zaWRlIGFuZCBvdXRzaWRlIG9mIHRoZSBjb250YWluZXIKIyMjCkJBU0hfRlJBTUVXT1JLX0xPR19GSUxFPSR7QkFTSF9GUkFNRVdPUktfTE9HX0ZJTEU6LSR7RlJBTUVXT1JLX1JPT1RfRElSfS9sb2dzL2Jhc2gubG9nfQoKIyMjCiMjIyBMT0cgTGV2ZWwKIyMjIG1pbmltdW0gbGV2ZWwgb2YgdGhlIG1lc3NhZ2VzIHRoYXQgd2lsbCBiZSBsb2dnZWQgaW50byBMT0dfRklMRQojIyMKIyMjIDA6IE5PIExPRwojIyMgMTogRVJST1IKIyMjIDI6IFdBUk5JTkcKIyMjIDM6IElORk8KIyMjIDQ6IERFQlVHCiMjIwpCQVNIX0ZSQU1FV09SS19MT0dfTEVWRUw9JHtCQVNIX0ZSQU1FV09SS19MT0dfTEVWRUw6LTB9CgojIGFic29sdXRlIGRpcmVjdG9yeSBjb250YWluaW5nIGRiIGltcG9ydCBzcWwgZHVtcHMKREJfSU1QT1JUX0RVTVBfRElSPSR7REJfSU1QT1JUX0RVTVBfRElSOi0ke0hPTUV9Ly5iYXNoLXRvb2xzL2RiSW1wb3J0RHVtcHN9CgojIGdhcmJhZ2UgY29sbGVjdCBhbGwgZmlsZXMgZm9yIHdoaWNoIG1vZGlmaWNhdGlvbiBpcyBncmVhdGVyIHRoYW4gZWc6IDMwIGRheXMgKCszMCkKIyBlYWNoIHRpbWUgYW4gZXhpc3RpbmcgZmlsZSBpcyB1c2VkIGJ5IGRiSW1wb3J0L2RiSW1wb3J0VGFibGUKIyB0aGUgZmlsZSBtb2RpZmljYXRpb24gdGltZSBpcyBzZXQgdG8gbm93CkRCX0lNUE9SVF9HQVJCQUdFX0NPTExFQ1RfREFZUz0ke0RCX0lNUE9SVF9HQVJCQUdFX0NPTExFQ1RfREFZUzotKzMwfQoKIyBhYnNvbHV0ZSBkaXJlY3RvcnkgY29udGFpbmluZyBkYlNjcmlwdHMgdXNlZCBieSBkYlNjcmlwdEFsbERhdGFiYXNlcwpTQ1JJUFRTX0ZPTERFUj0ke1NDUklQVFNfRk9MREVSOi0ke0hPTUV9Ly5iYXNoLXRvb2xzL2NvbmYvZGJTY3JpcHRzfQoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIEFXUyBQYXJhbWV0ZXJzCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KUzNfQkFTRV9VUkw9JHtTM19CQVNFX1VSTDotfQoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIFBvc3RtYW4gUGFyYW1ldGVycwojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tClBPU1RNQU5fQVBJX0tFWT0K" \
-  "755"
-
-declare -gx embed_file_bashToolsDefaultConfigTemplate="${PERSISTENT_TMPDIR:-/tmp}/db87222729e0f1ed9c597a486a61a08c/bashToolsDefaultConfigTemplate"
-
   BASH_TOOLS_ROOT_DIR="$(cd "${CURRENT_DIR}/${RELATIVE_FRAMEWORK_DIR_TO_CURRENT_DIR}" && pwd -P)"
   if [[ -d "${BASH_TOOLS_ROOT_DIR}/vendor/bash-tools-framework/" ]]; then
     FRAMEWORK_ROOT_DIR="$(cd "${BASH_TOOLS_ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
@@ -377,7 +438,7 @@ declare -gx embed_file_bashToolsDefaultConfigTemplate="${PERSISTENT_TMPDIR:-/tmp
     (
       echo "#!/usr/bin/env bash"
       # shellcheck disable=SC2154
-      echo "${embed_file_bashToolsDefaultConfigTemplate}"
+      echo "${bashToolsDefaultConfigTemplate}"
     ) >"${envFile}"
     Log::displayInfo "Configuration file '${envFile}' created"
   else
@@ -390,7 +451,7 @@ declare -gx embed_file_bashToolsDefaultConfigTemplate="${PERSISTENT_TMPDIR:-/tmp
       ) >>"${envFile}"
     fi
   fi
-  # shellcheck source=/conf/.env
+  # shellcheck source=/conf/defaultEnv/.env
   source "${envFile}" || {
     Log::displayError "impossible to load '${envFile}'"
     exit 1
@@ -1388,6 +1449,7 @@ beforeParseCallback() {
 
 copyrightCallback() {
   #
+  # shellcheck disable=SC2155,SC2154,SC2250
   echo "Copyright (c) 2020-now François Chastanet"
 }
 
@@ -1429,16 +1491,6 @@ optionVersionCallback() {
   # shellcheck disable=SC2154
   echo "${SCRIPT_NAME} version 3.0"
   exit 0
-}
-
-# shellcheck disable=SC2317 # if function is overridden
-optionEnvFileCallback() {
-  local envFile="$2"
-  Log::displayWarning "Command ${SCRIPT_NAME} - Option --env-file is deprecated and will be removed in the future"
-  if [[ ! -f "${envFile}" || ! -r "${envFile}" ]]; then
-    Log::displayError "Command ${SCRIPT_NAME} - Option --env-file - File '${envFile}' doesn't exist"
-    exit 1
-  fi
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1615,9 +1667,6 @@ commandOptionParseFinished() {
   defaultEnvFile="${PERSISTENT_TMPDIR}/.framework-config"
   echo "${defaultFrameworkConfig}" >"${defaultEnvFile}"
   local -a files=("${defaultEnvFile}")
-  if [[ -f "${envFile}" ]]; then
-    files+=("${envFile}")
-  fi
   # shellcheck disable=SC2154
   if [[ -f "${optionBashFrameworkConfig}" ]]; then
     files+=("${optionBashFrameworkConfig}")
@@ -1633,11 +1682,15 @@ commandOptionParseFinished() {
 
 
 
-beforeParseCallback() {
+defaultBeforeParseCallback() {
   BashTools::Conf::requireLoad
   Env::requireLoad
   UI::requireTheme
   Log::requireLoad
+}
+
+beforeParseCallback() {
+  defaultBeforeParseCallback
 }
 
 
@@ -1657,6 +1710,24 @@ optionJobsCallback() {
   if [[ ${optionJobs} -lt 1 ]]; then
     Log::fatal "number of jobs must be greater than 0"
   fi
+}
+
+
+
+fromDsnOptionLongDescription() {
+  local dsnList=""
+  dsnList="$(Conf::getMergedList "dsn" "env" "      - ")"
+
+  echo -e "  ${__HELP_TITLE}Data Source Name (DSN)${__HELP_NORMAL}"
+  echo -e "    ${__HELP_TITLE}Default dsn directory:${__HELP_NORMAL}"
+  echo -e "      ${BASH_TOOLS_ROOT_DIR}/conf/dsn"
+  echo
+  echo -e "    ${__HELP_TITLE}User dsn directory:${__HELP_NORMAL}"
+  echo -e "      ${HOME}/.bash-tools/dsn"
+  echo -e '      Allows to override dsn defined in "Default dsn directory"'
+  echo
+  echo -e "    ${__HELP_TITLE}List of available dsn:${__HELP_NORMAL}"
+  echo -e "${dsnList}"
 }
 
 
@@ -1681,10 +1752,7 @@ declare copyrightBeginYear="2020"
 declare defaultFromDsn="default.remote"
 
 beforeParseCallback() {
-  BashTools::Conf::requireLoad
-  Env::requireLoad
-  UI::requireTheme
-  Log::requireLoad
+  defaultBeforeParseCallback
   Linux::requireExecutedAsUser
   Linux::requireRealpathCommand
 }
@@ -1716,33 +1784,34 @@ optionSeparatorCallback() {
 longDescriptionFunction() {
   local example1=$'dbQueryAllDatabases databaseSize -j 12 --separator "|" --bar 2>/dev/null | column -s "|" -t -n -c 40'
 
-  local dsnList queriesList
-  dsnList="$(Conf::getMergedList "dsn" "env" "    - ")"
-  queriesList="$(Conf::getMergedList "dbQueries" "sql" "    - " || true)"
+  local queriesList
+  queriesList="$(Conf::getMergedList "dbQueries" "sql" "      - " || true)"
 
-  echo -e "${__HELP_TITLE}  LIST OF AVAILABLE DSN:${__HELP_NORMAL}"
-  echo -e "${dsnList}"
+  fromDsnOptionLongDescription
   echo
-  echo -e "${__HELP_TITLE}  DEFAULT QUERIES DIRECTORY:${__HELP_NORMAL}"
-  echo -e "    ${QUERIES_DIR-configuration error}"
+  echo -e "  ${__HELP_TITLE}QUERIES${__HELP_NORMAL}"
+  echo -e "    ${__HELP_TITLE}Default queries directory:${__HELP_NORMAL}"
+  echo -e "      ${QUERIES_DIR-configuration error}"
   echo
-  echo -e "${__HELP_TITLE}  USER QUERIES DIRECTORY:${__HELP_NORMAL}"
-  echo -e "    ${HOME_QUERIES_DIR-configuration error}"
-  echo -e "    Allows to override queries defined in 'Default queries directory'"
+  echo -e "    ${__HELP_TITLE}User queries directory:${__HELP_NORMAL}"
+  echo -e "      ${HOME_QUERIES_DIR-configuration error}"
+  echo -e "      Allows to override queries defined in 'Default queries directory'"
   echo
-  echo -e "${__HELP_TITLE}  LIST OF AVAILABLE QUERIES:${__HELP_NORMAL}"
+  echo -e "    ${__HELP_TITLE}List of available queries:${__HELP_NORMAL}"
   echo -e "${queriesList}"
   echo
-  echo -e "${__HELP_TITLE}  EXAMPLES:${__HELP_NORMAL}"
+  echo -e "  ${__HELP_TITLE}EXAMPLES:${__HELP_NORMAL}"
   echo -e "    ${__HELP_EXAMPLE}${example1}${__HELP_NORMAL}"
 }
 
 argQueryHelpFunction() {
-  Array::wrap2 " " 80 6 \
-    "    Query to execute" "\n" \
-    "- <file>, try to execute the mysql query provided by the file" "\n" \
-    '- <queryFile>, search for query file in queries directory (see below)' "\n" \
-    '- else the argument is interpreted as query string'
+  echo "    Query to execute"
+  echo "      - <file>, try to execute the mysql query"
+  echo "        provided by the file"
+  echo '      - <queryFile>, search for query file in'
+  echo '        queries directory (see below)'
+  echo '      - else the argument is interpreted as'
+  echo '        query string'
 }
 
 dbQueryAllDatabasesEveryArgumentCallback() {
@@ -1788,7 +1857,6 @@ declare optionBashFrameworkConfig=""
 declare optionInfoVerbose="0"
 declare optionDebugVerbose="0"
 declare optionTraceVerbose="0"
-declare -a optionEnvFiles=()
 declare optionLogLevel=""
 declare optionLogFile=""
 declare optionDisplayLevel=""
@@ -1830,7 +1898,6 @@ dbQueryAllDatabasesCommandParse() {
   optionTraceVerbose="0"
   local -i options_parse_optionParsedCountOptionTraceVerbose
   ((options_parse_optionParsedCountOptionTraceVerbose = 0)) || true
-
   optionLogLevel=""
   local -i options_parse_optionParsedCountOptionLogLevel
   ((options_parse_optionParsedCountOptionLogLevel = 0)) || true
@@ -1867,7 +1934,7 @@ dbQueryAllDatabasesCommandParse() {
     local options_parse_arg="$1"
     local argOptDefaultBehavior=0
     case "${options_parse_arg}" in
-      # Option 1/18
+      # Option 1/17
       # optionJobs alts --jobs|-j
       # type: String min 0 max 1
       --jobs | -j)
@@ -1888,7 +1955,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 2/18
+      # Option 2/17
       # optionProgressBar alts --bar|-b
       # type: Boolean min 0 max 1
       --bar | -b)
@@ -1904,7 +1971,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 3/18
+      # Option 3/17
       # optionFromDsn alts --from-dsn|-f
       # type: String min 0 max 1
       --from-dsn | -f)
@@ -1923,7 +1990,7 @@ dbQueryAllDatabasesCommandParse() {
         optionFromDsn="$1"
         ;;
 
-      # Option 4/18
+      # Option 4/17
       # optionHelp alts --help|-h
       # type: Boolean min 0 max 1
       --help | -h)
@@ -1939,7 +2006,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 5/18
+      # Option 5/17
       # optionConfig alts --config
       # type: Boolean min 0 max 1
       --config)
@@ -1953,7 +2020,7 @@ dbQueryAllDatabasesCommandParse() {
         ((++options_parse_optionParsedCountOptionConfig))
         ;;
 
-      # Option 6/18
+      # Option 6/17
       # optionBashFrameworkConfig alts --bash-framework-config
       # type: String min 0 max 1
       --bash-framework-config)
@@ -1974,7 +2041,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 7/18
+      # Option 7/17
       # optionInfoVerbose alts --verbose|-v
       # type: Boolean min 0 max 1
       --verbose | -v)
@@ -1992,7 +2059,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 8/18
+      # Option 8/17
       # optionDebugVerbose alts -vv
       # type: Boolean min 0 max 1
       -vv)
@@ -2010,7 +2077,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 9/18
+      # Option 9/17
       # optionTraceVerbose alts -vvv
       # type: Boolean min 0 max 1
       -vvv)
@@ -2028,25 +2095,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 10/18
-      # optionEnvFiles alts --env-file
-      # type: StringArray min 0 max -1
-      --env-file)
-        shift
-        if (($# == 0)); then
-          Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - a value needs to be specified"
-          return 1
-        fi
-
-        ((++options_parse_optionParsedCountOptionEnvFiles))
-        optionEnvFiles+=("$1")
-        optionEnvFileCallback "${options_parse_arg}" "${optionEnvFiles[@]}"
-
-        updateArgListEnvFileCallback "${options_parse_arg}" "${optionEnvFiles[@]}"
-
-        ;;
-
-      # Option 11/18
+      # Option 10/17
       # optionLogLevel alts --log-level
       # type: String min 0 max 1
       # authorizedValues: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE
@@ -2074,7 +2123,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 12/18
+      # Option 11/17
       # optionLogFile alts --log-file
       # type: String min 0 max 1
       --log-file)
@@ -2097,7 +2146,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 13/18
+      # Option 12/17
       # optionDisplayLevel alts --display-level
       # type: String min 0 max 1
       # authorizedValues: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE
@@ -2125,7 +2174,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 14/18
+      # Option 13/17
       # optionNoColor alts --no-color
       # type: Boolean min 0 max 1
       --no-color)
@@ -2143,7 +2192,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 15/18
+      # Option 14/17
       # optionTheme alts --theme
       # type: String min 0 max 1
       # authorizedValues: default|default-force|noColor
@@ -2171,7 +2220,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 16/18
+      # Option 15/17
       # optionVersion alts --version
       # type: Boolean min 0 max 1
       --version)
@@ -2187,7 +2236,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 17/18
+      # Option 16/17
       # optionQuiet alts --quiet|-q
       # type: Boolean min 0 max 1
       --quiet | -q)
@@ -2205,7 +2254,7 @@ dbQueryAllDatabasesCommandParse() {
 
         ;;
 
-      # Option 18/18
+      # Option 17/17
       # optionSeparator alts --separator|-s
       # type: String min 0 max 1
       --separator | -s)
@@ -2295,7 +2344,6 @@ dbQueryAllDatabasesCommandParse() {
 
 
 
-
   if ((options_parse_argParsedCountArgQuery < 1 )); then
     Log::displayError "Command ${SCRIPT_NAME} - Argument 'argQuery' should be provided at least 1 time(s)"
     return 1
@@ -2310,7 +2358,7 @@ dbQueryAllDatabasesCommandParse() {
 # @description display command options and arguments help for dbQueryAllDatabasesCommand
 dbQueryAllDatabasesCommandHelp() {
   echo -e "${__HELP_TITLE_COLOR}SYNOPSIS:${__RESET_COLOR}"
-  Array::wrap2 ' ' 76 4 "    " "Execute a query on multiple databases to generate a tsv format report.\\n The query can be parallelized on multiple databases."
+  Array::wrap2 ' ' 76 4 "    " "Execute a query on multiple databases to generate a tsv format report." "The query can be parallelized on multiple databases."
 
   echo
   echo
@@ -2323,7 +2371,7 @@ dbQueryAllDatabasesCommandHelp() {
   # ------------------------------------------
   # usage/options section
   # ------------------------------------------
-  optionsAltList=("[--jobs|-j <jobsCount>]" "[--bar|-b]" "[--from-dsn|-f <dsn>]" "[--help|-h]" "[--config]" "[--bash-framework-config <bash-framework-config>]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--env-file <env-file>]" "[--log-level <log-level>]" "[--log-file <log-file>]" "[--display-level <display-level>]" "[--no-color]" "[--theme <theme>]" "[--version]" "[--quiet|-q]" "[--separator|-s <separator>]"
+  optionsAltList=("[--jobs|-j <jobsCount>]" "[--bar|-b]" "[--from-dsn|-f <dsn>]" "[--help|-h]" "[--config]" "[--bash-framework-config <bash-framework-config>]" "[--verbose|-v]" "[-vv]" "[-vvv]" "[--log-level <log-level>]" "[--log-file <log-file>]" "[--display-level <display-level>]" "[--no-color]" "[--theme <theme>]" "[--version]" "[--quiet|-q]" "[--separator|-s <separator>]"
   )
   Array::wrap2 " " 80 2 "${__HELP_TITLE_COLOR}USAGE:${__RESET_COLOR}" \
     "dbQueryAllDatabases" "${optionsAltList[@]}"
@@ -2353,7 +2401,7 @@ dbQueryAllDatabasesCommandHelp() {
   echo
 
   echo -e "  ${__HELP_OPTION_COLOR}--bar${__HELP_NORMAL}, ${__HELP_OPTION_COLOR}-b${__HELP_NORMAL} {single}"
-  Array::wrap2 ' ' 76 4 "    " "Show progress as a progress bar. In the bar is shown: % of jobs completed," "estimated seconds left, and number of jobs started." ""
+  Array::wrap2 ' ' 76 4 "    " "Show progress as a progress bar. In the bar is shown: % of jobs" "completed, estimated seconds left, and number of jobs started."
   echo
 
 
@@ -2398,12 +2446,6 @@ dbQueryAllDatabasesCommandHelp() {
 
   echo -e "  ${__HELP_OPTION_COLOR}-vvv${__HELP_NORMAL} {single}"
   Array::wrap2 ' ' 76 4 "    " "Trace level verbose mode (alias of --display-level TRACE)"
-  echo
-
-
-
-  echo -e "  ${__HELP_OPTION_COLOR}--env-file <env-file>${__HELP_NORMAL} {list} (optional)"
-  Array::wrap2 ' ' 76 4 "    " "Load the specified env file (deprecated, please use --bash-framework-config option instead)"
   echo
 
 
