- renamed ROOT_DIR to FRAMEWORK_ROOT_DIR or BASH_TOOLS_ROOT_DIR - renamed BIN_DIR to COMMAND_BIN_DIR - cut header.tpl in _header.tpl and _load.tpl - removed other _header*.tpl files

diff --git a/bin/doc b/bin/doc
--- a/bin/doc
+++ b/bin/doc
@@ -14,7 +14,8 @@ SCRIPT_NAME=${0##*/}
 REAL_SCRIPT_FILE="$(readlink -e "$(realpath "${BASH_SOURCE[0]}")")"
 # shellcheck disable=SC2034
 CURRENT_DIR="$(cd "$(readlink -e "${REAL_SCRIPT_FILE%/*}")" && pwd -P)"
-BIN_DIR="${CURRENT_DIR}"
+# shellcheck disable=SC2034
+COMMAND_BIN_DIR="${CURRENT_DIR}"
 
 if [[ -t 1 || -t 2 ]]; then
   # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
@@ -115,6 +116,34 @@ export TERM=xterm-256color
 export DEBIAN_FRONTEND=noninteractive
 export DEBCONF_NONINTERACTIVE_SEEN=true
 
+BASH_TOOLS_ROOT_DIR="$(cd "${CURRENT_DIR}/.." && pwd -P)"
+if [[ -d "${BASH_TOOLS_ROOT_DIR}/vendor/bash-tools-framework/" ]]; then
+  FRAMEWORK_ROOT_DIR="$(cd "${BASH_TOOLS_ROOT_DIR}/vendor/bash-tools-framework" && pwd -P)"
+else
+  # if the directory does not exist yet, give a value to FRAMEWORK_ROOT_DIR
+  FRAMEWORK_ROOT_DIR="${BASH_TOOLS_ROOT_DIR}/vendor/bash-tools-framework"
+fi
+export BASH_TOOLS_ROOT_DIR FRAMEWORK_ROOT_DIR
+
+if [[ -f "${HOME}/.bash-tools/.env" ]]; then
+  export BASH_FRAMEWORK_ENV_FILEPATH="${HOME}/.bash-tools/.env"
+fi
+BASH_TOOLS_ROOT_DIR="$(cd "${CURRENT_DIR}/.." && pwd -P)"
+
+# shellcheck disable=SC2034
+
+COMMAND_BIN_DIR="${CURRENT_DIR}"
+if [[ -n "${FRAMEWORK_ROOT_DIR+xxx}" ]]; then
+  # shellcheck disable=SC2034
+  FRAMEWORK_SRC_DIR="${FRAMEWORK_ROOT_DIR}/src"
+  # shellcheck disable=SC2034
+  FRAMEWORK_BIN_DIR="${FRAMEWORK_ROOT_DIR}/bin"
+  # shellcheck disable=SC2034
+  FRAMEWORK_VENDOR_DIR="${FRAMEWORK_ROOT_DIR}/vendor"
+  # shellcheck disable=SC2034
+  FRAMEWORK_VENDOR_BIN_DIR="${FRAMEWORK_ROOT_DIR}/vendor/bin"
+fi
+
 Args::defaultHelp() {
   local helpArg=$1
   shift || true
@@ -173,8 +202,8 @@ declare -g BASH_FRAMEWORK_CACHED_ENV_FILE
 declare -g BASH_FRAMEWORK_DEFAULT_ENV_FILE
 
 # load variables in order(from less specific to more specific) from :
-# - ${ROOT_DIR}/src/Env/testsData/.env file
-# - ${ROOT_DIR}/conf/.env file if exists
+# - ${FRAMEWORK_ROOT_DIR}/src/Env/testsData/.env file
+# - ${FRAMEWORK_ROOT_DIR}/conf/.env file if exists
 # - ~/.env file if exists
 # - ~/.bash-tools/.env file if exists
 # - BASH_FRAMEWORK_ENV_FILEPATH=<fullPathToEnvFile or empty if no file to be loaded>
@@ -188,7 +217,7 @@ Env::load() {
   (
     echo "BASH_FRAMEWORK_LOG_LEVEL=${BASH_FRAMEWORK_LOG_LEVEL:-0}"
     echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${BASH_FRAMEWORK_DISPLAY_LEVEL:-3}"
-    echo "BASH_FRAMEWORK_LOG_FILE=${BASH_FRAMEWORK_LOG_FILE:-${ROOT_DIR}/logs/${SCRIPT_NAME}.log}"
+    echo "BASH_FRAMEWORK_LOG_FILE=${BASH_FRAMEWORK_LOG_FILE:-${FRAMEWORK_ROOT_DIR}/logs/${SCRIPT_NAME}.log}"
     echo "BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION=${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION:-5}"
   ) >"${BASH_FRAMEWORK_DEFAULT_ENV_FILE}"
 
@@ -201,8 +230,8 @@ Env::load() {
     if [[ -f "${BASH_FRAMEWORK_DEFAULT_ENV_FILE}" ]]; then
       files+=("${BASH_FRAMEWORK_DEFAULT_ENV_FILE}")
     fi
-    if [[ -f "${ROOT_DIR}/conf/.env" && -r "${ROOT_DIR}/conf/.env" ]]; then
-      files+=("${ROOT_DIR}/conf/.env")
+    if [[ -f "${FRAMEWORK_ROOT_DIR}/conf/.env" && -r "${FRAMEWORK_ROOT_DIR}/conf/.env" ]]; then
+      files+=("${FRAMEWORK_ROOT_DIR}/conf/.env")
     fi
     if [[ -f "${HOME}/.env" && -r "${HOME}/.env" ]]; then
       files+=("${HOME}/.env")
@@ -439,7 +468,7 @@ ShellDoc::generateMdFileFromTemplate() {
       ( #
         (cd "${fromDir}" && "${relativeFile}" --help) |
           File::replaceTokenByInput "@@@${token}_help@@@" "${targetFile}"
-      ) || Log::displayError "$(realpath "${fromDir}/${relativeFile}" --relative-to="${ROOT_DIR}") --help error caught"
+      ) || Log::displayError "$(realpath "${fromDir}/${relativeFile}" --relative-to="${FRAMEWORK_ROOT_DIR}") --help error caught"
     else
       ((++tokenNotFoundCount))
       Log::displayWarning "token ${token} not found in ${targetFile}"
@@ -687,53 +716,16 @@ Args::parseVerbose "${__LEVEL_INFO}" "$@" || true
 declare -a args=("$@")
 Array::remove args -v --verbose
 set -- "${args[@]}"
+
 Log::load
 
-Env::pathPrepend "${BIN_DIR}"
+Env::pathPrepend "${COMMAND_BIN_DIR}"
 
 # prepare bin directory for eventual bin files generated by Embed::embed
 mkdir -p "${TMPDIR:-/tmp}/bin"
 Env::pathPrepend "${TMPDIR:-/tmp}/bin"
-
-if [[ -t 1 || -t 2 ]]; then
-  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  export __ERROR_COLOR='\e[31m'      # Red
-  export __INFO_COLOR='\e[44m'       # white on lightBlue
-  export __SUCCESS_COLOR='\e[32m'    # Green
-  export __WARNING_COLOR='\e[33m'    # Yellow
-  export __TEST_COLOR='\e[100m'      # Light magenta
-  export __TEST_ERROR_COLOR='\e[41m' # white on red
-  export __SKIPPED_COLOR='\e[33m'    # Yellow
-  export __HELP_COLOR='\e[7;49;33m'  # Black on Gold
-  export __DEBUG_COLOR='\e[37m'      # Grey
-  # Internal: reset color
-  export __RESET_COLOR='\e[0m' # Reset Color
-  # shellcheck disable=SC2155,SC2034
-  export __HELP_EXAMPLE="$(echo -e "\e[1;30m")"
-  # shellcheck disable=SC2155,SC2034
-  export __HELP_TITLE="$(echo -e "\e[1;37m")"
-  # shellcheck disable=SC2155,SC2034
-  export __HELP_NORMAL="$(echo -e "\033[0m")"
-else
-  # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
-  export __ERROR_COLOR=''
-  export __INFO_COLOR=''
-  export __SUCCESS_COLOR=''
-  export __WARNING_COLOR=''
-  export __SKIPPED_COLOR=''
-  export __HELP_COLOR=''
-  export __TEST_COLOR=''
-  export __TEST_ERROR_COLOR=''
-  export __DEBUG_COLOR=''
-  # Internal: reset color
-  export __RESET_COLOR=''
-  export __HELP_EXAMPLE=''
-  export __HELP_TITLE=''
-  export __HELP_NORMAL=''
-fi
-ROOT_DIR="$(cd "${CURRENT_DIR}/.." && pwd -P)"
-DOC_DIR="${ROOT_DIR}/pages"
-HELP="$(
+DOC_DIR="${BASH_TOOLS_ROOT_DIR}/pages"
+showHelp() {
   cat <<EOF
 ${__HELP_TITLE}Description:${__HELP_NORMAL} generate markdown documentation
 ${__HELP_TITLE}Usage:${__HELP_NORMAL} ${SCRIPT_NAME}
@@ -749,12 +741,12 @@ MIT License
 
 Copyright (c) 2022 François Chastanet
 EOF
-)"
-Args::defaultHelp "${HELP}" "$@"
+}
+Args::defaultHelp showHelp "$@"
 
 if [[ "${IN_BASH_DOCKER:-}" != "You're in docker" ]]; then
   DOCKER_RUN_OPTIONS=$"-e ORIGINAL_DOC_DIR=${DOC_DIR}" \
-    "${BIN_DIR}/runBuildContainer" "/bash/bin/doc" "$@"
+    "${COMMAND_BIN_DIR}/runBuildContainer" "/bash/bin/doc" "$@"
   exit $?
 fi
 
@@ -764,7 +756,7 @@ fi
 mkdir -p "${HOME}/.bash-tools"
 
 (
-  cd "${ROOT_DIR}" || exit 1
+  cd "${BASH_TOOLS_ROOT_DIR}" || exit 1
   cp -R conf/. "${HOME}/.bash-tools"
   sed -i \
     -e "s@^S3_BASE_URL=.*@S3_BASE_URL=s3://example.com/exports/@g" \
@@ -782,22 +774,23 @@ export PATH=/tmp:${PATH}
 Log::displayInfo 'generate Commands.md'
 ((TOKEN_NOT_FOUND_COUNT = 0)) || true
 ShellDoc::generateMdFileFromTemplate \
-  "${ROOT_DIR}/Commands.tmpl.md" \
+  "${BASH_TOOLS_ROOT_DIR}/Commands.tmpl.md" \
   "${DOC_DIR}/Commands.md" \
-  "${BIN_DIR}" \
-  TOKEN_NOT_FOUND_COUNT
+  "${FRAMEWORK_BIN_DIR}" \
+  TOKEN_NOT_FOUND_COUNT \
+  '(bash-tpl|plantuml|definitionLint|compile)$'
 
 # inject plantuml diagram source code into command
 sed -E -i \
-  -e "/@@@mysql2puml_plantuml_diagram@@@/r ${ROOT_DIR}/src/_binaries/Converters/testsData/mysql2puml.puml" \
+  -e "/@@@mysql2puml_plantuml_diagram@@@/r ${BASH_TOOLS_ROOT_DIR}/src/_binaries/Converters/testsData/mysql2puml.puml" \
   -e "/@@@mysql2puml_plantuml_diagram@@@/d" \
   "${DOC_DIR}/Commands.md"
 
 mkdir -p "${DOC_DIR}/src/_binaries/Converters/testsData" || true
-cp "${ROOT_DIR}/src/_binaries/Converters/testsData/mysql2puml-model.png" "${DOC_DIR}/src/_binaries/Converters/testsData"
+cp "${BASH_TOOLS_ROOT_DIR}/src/_binaries/Converters/testsData/mysql2puml-model.png" "${DOC_DIR}/src/_binaries/Converters/testsData"
 
 # copy other files
-cp "${ROOT_DIR}/README.md" "${DOC_DIR}/README.md"
+cp "${BASH_TOOLS_ROOT_DIR}/README.md" "${DOC_DIR}/README.md"
 sed -i -E \
   -e '/<!-- remove -->/,/<!-- endRemove -->/d' \
   -e 's#https://fchastanet.github.io/bash-tools/#/#' \
