bin/doc fails if some token are missing from Commands.md

diff --git a/bin/doc b/bin/doc
--- a/bin/doc
+++ b/bin/doc
@@ -64,6 +64,35 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 
 # FUNCTIONS
 
+Args::showHelp() {
+  local helpArg="$1"
+  echo -e "${helpArg}"
+}
+
+Args::defaultHelpNoExit() {
+  local helpArg="$1"
+  shift || true
+  # shellcheck disable=SC2034
+  local args
+  args="$(getopt -l help -o h -- "$@" 2>/dev/null)" || true
+  eval set -- "${args}"
+
+  while true; do
+    case $1 in
+      -h | --help)
+        Args::showHelp "${helpArg}"
+        return 1
+        ;;
+      --)
+        break
+        ;;
+      *)
+        # ignore
+        ;;
+    esac
+  done
+}
+
 # *Public*: run command and store data in following global variables :
 # * bash_framework_status the exit status of the command
 # * bash_framework_duration the duration of the command
@@ -94,6 +123,12 @@ Framework::run() {
   end=$(date +%s)
   # shellcheck disable=SC2034
   bash_framework_duration=$((end - start))
+}
+
+Args::defaultHelp() {
+  if ! Args::defaultHelpNoExit "$@"; then
+    exit 0
+  fi
 }
 
 Filters::escapeColorCodes() {
@@ -187,6 +222,10 @@ if [[ "${IN_BASH_DOCKER:-}" != "You're in docker" ]]; then
   exit $?
 fi
 
+Args::defaultHelp "Generate Jekyll documentation" "$@"
+
+((TOKEN_NOT_FOUND_COUNT = 0)) || true
+
 replaceTokenByInput() {
   local token="$1"
   local targetFile="$2"
@@ -210,21 +249,21 @@ generateMdFileFromTemplate() {
   local fromDir="$3"
 
   cp "${templateFile}" "${targetFile}"
-  (
-    while IFS= read -r relativeFile; do
-      local token="${relativeFile#./}"
-      token="${token////_}"
-      if grep -q "@@@${token}_help@@@" "${targetFile}"; then
-        Log::displayInfo "generate help for ${token}"
-        ( #
-          (cd "${fromDir}" && "${relativeFile}" --help) |
-            replaceTokenByInput "@@@${token}_help@@@" "${targetFile}"
-        ) || Log::displayError "$(realpath "${fromDir}/${relativeFile}" --relative-to="${ROOT_DIR}") --help error caught"
-      elif [[ "${token}" != "${SCRIPT_NAME}" ]]; then
-        Log::displayWarning "token ${token} not found in ${targetFile}"
-      fi
-    done < <(cd "${fromDir}" && find . -type f -executable)
-  )
+
+  while IFS= read -r relativeFile; do
+    local token="${relativeFile#./}"
+    token="${token////_}"
+    if grep -q "@@@${token}_help@@@" "${targetFile}"; then
+      Log::displayInfo "generate help for ${token}"
+      ( #
+        (cd "${fromDir}" && "${relativeFile}" --help) |
+          replaceTokenByInput "@@@${token}_help@@@" "${targetFile}"
+      ) || Log::displayError "$(realpath "${fromDir}/${relativeFile}" --relative-to="${ROOT_DIR}") --help error caught"
+    else
+      ((++TOKEN_NOT_FOUND_COUNT))
+      Log::displayWarning "token ${token} not found in ${targetFile}"
+    fi
+  done < <(cd "${fromDir}" && find . -type f -executable)
 }
 
 #-----------------------------
@@ -249,19 +288,21 @@ export PATH=/tmp:${PATH}
 # doc generation
 #-----------------------------
 
-(
-  Log::displayInfo 'generate Commands.md'
-  generateMdFileFromTemplate \
-    "${ROOT_DIR}/Commands.tmpl.md" \
-    "${DOC_DIR}/Commands.md" \
-    "${BIN_DIR}"
+Log::displayInfo 'generate Commands.md'
+generateMdFileFromTemplate \
+  "${ROOT_DIR}/Commands.tmpl.md" \
+  "${DOC_DIR}/Commands.md" \
+  "${BIN_DIR}"
 
-  # inject plantuml diagram source code into command
-  sed -i \
-    -e "/@@@mysql2puml_plantuml_diagram@@@/r ${ROOT_DIR}/tests/tools/data/mysql2puml.puml" \
-    -e "/@@@mysql2puml_plantuml_diagram@@@/d" \
-    "${DOC_DIR}/Commands.md"
+# inject plantuml diagram source code into command
+sed -i \
+  -e "/@@@mysql2puml_plantuml_diagram@@@/r ${ROOT_DIR}/tests/tools/data/mysql2puml.puml" \
+  -e "/@@@mysql2puml_plantuml_diagram@@@/d" \
+  "${DOC_DIR}/Commands.md"
 
-  # copy other files
-  cp "${ROOT_DIR}/README.md" "${DOC_DIR}/README.md"
-)
+# copy other files
+cp "${ROOT_DIR}/README.md" "${DOC_DIR}/README.md"
+
+if ((TOKEN_NOT_FOUND_COUNT > 0)); then
+  exit 1
+fi
