update binaries after bash -framework update

diff --git a/bin/doc b/bin/doc
--- a/bin/doc
+++ b/bin/doc
@@ -311,13 +311,6 @@ Log::displaySuccess() {
   Log::logSuccess "$1"
 }
 
-# Display message using error color (red) and exit immediately with error status 1
-# @param {String} $1 message
-Log::fatal() {
-  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
-  exit 1
-}
-
 # log message to file
 # @param {String} $1 message
 Log::logDebug() {
@@ -328,12 +321,6 @@ Log::logDebug() {
 # @param {String} $1 message
 Log::logError() {
   Log::logMessage "ERROR" "$@"
-}
-
-# log message to file
-# @param {String} $1 message
-Log::logFatal() {
-  Log::logMessage "FATAL" "$@"
 }
 
 # log message to file
@@ -386,6 +373,14 @@ Args::showHelp() {
   echo -e "${helpArg}"
 }
 
+# Display message using error color (red) and exit immediately with error status 1
+# @param {String} $1 message
+Log::fatal() {
+  echo -e "${__ERROR_COLOR}FATAL   - ${1}${__RESET_COLOR}" >&2
+  Log::logFatal "$1"
+  exit 1
+}
+
 # Internal: common log message
 #
 # **Arguments**:
@@ -407,6 +402,12 @@ Log::logMessage() {
     date="$(date '+%Y-%m-%d %H:%M:%S')"
     printf "%s|%7s|%s\n" "${date}" "${levelMsg}" "${msg}" >>"${BASH_FRAMEWORK_LOG_FILE}"
   fi
+}
+
+# log message to file
+# @param {String} $1 message
+Log::logFatal() {
+  Log::logMessage "FATAL" "$@"
 }
 
 # FUNCTIONS
@@ -464,9 +465,6 @@ if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_WARNING)); then
 fi
 if ((BASH_FRAMEWORK_LOG_LEVEL < __LEVEL_ERROR)); then
   Log::logError() { :; }
-  Log::logFatal() {
-    Log::fatal "$1"
-  }
 fi
 
 DOC_DIR="${ROOT_DIR}/jekyll"
@@ -487,7 +485,7 @@ ${__HELP_TITLE}Author:${__HELP_NORMAL}
 ${__HELP_TITLE}License:${__HELP_NORMAL}
 MIT License
 
-Copyright (c) 2020 Scrasnups
+Copyright (c) 2022 François Chastanet
 EOF
 )"
 Args::defaultHelp "${HELP}" "$@"
