GitHub Release Manager - use parallel or xargs
- use parallel or xargs
- improved validation performances

diff --git a/bin/githubReleaseManager b/bin/githubReleaseManager
--- a/bin/githubReleaseManager
+++ b/bin/githubReleaseManager
@@ -1754,8 +1754,15 @@ validateYamlConfig() {
   local errors=0
   Log::displayInfo "Validating configuration file ${configFile}"
 
+  local missingFields
+  missingFields="$(yq eval '.softwares[] | select( has("id") and has("url") and has("version") and has("targetFile") and has("versionArg") | not) | .id // "[unknown]"' "${configFile}")"
+  if [[ "${missingFields}" != '[unknown]' ]]; then
+    Log::displayError "Missing required fields in software entries: ${missingFields}"
+    ((errors++))
+  fi
+
   # Check if softwares key exists and is an array
-  if ! yq '.softwares | type' "${configFile}" | grep -q "array"; then
+  if ! yq '.softwares | type' "${configFile}" | grep -q "!!seq"; then
     Log::displayError "Configuration file must have a 'softwares' array"
     ((errors++))
   fi
@@ -2410,15 +2417,30 @@ importInstallCallbacks() {
 
 forEachSoftware() {
   local configFile="${1}"
-  shift 2 || true
-  local softwareIds=("$@")
+  shift || true
+  local -a softwareIds=("$@")
 
+  local theme="${optionTheme}"
+  if [[ "${theme}" != "noColor" ]]; then
+    theme="default-force"
+  fi
   # Run installations in parallel using xargs
-  printf "%s\n" "${softwareIds[@]}" |
-    SKIP_YAML_CHECKS=1 xargs -P "$(nproc)" -I {} \
-      "${BASH_SOURCE[0]}" \
-      -c "${optionConfigFile}" \
-      "{}" 2>&1
+  local cmd="${BASH_SOURCE[0]}"
+  export cmd optionConfigFile theme
+  callSoft() {
+    local soft="$1"
+    SKIP_YAML_CHECKS=1 LOG_CONTEXT="Software ${soft} - " "${cmd}" \
+      --theme "${theme}" -c "${optionConfigFile}" "${soft}"
+  }
+  export -f callSoft
+
+  if command -v parallel &>/dev/null; then
+    parallel -j "$(nproc)" callSoft ::: "${softwareIds[@]}"
+  else
+    printf "%s\n" "${softwareIds[@]}" |
+      xargs --no-run-if-empty -n 1 -P "$(nproc)" -I {} bash -c 'callSoft "$@"' _ {}
+  fi
+
 }
 
 processSingleSoftware() {
@@ -2430,16 +2452,25 @@ processSingleSoftware() {
   # shellcheck disable=SC2034
   LOG_CONTEXT="Software ${softwareId} - "
   if [[ -n "${software}" ]]; then
-    url="$(echo "${software}" | yq --raw-output '.url' -)"
-    version="$(echo "${software}" | yq --raw-output '.version' -)"
-    versionArg="$(echo "${software}" | yq --raw-output '.versionArg' -)"
-    targetFile="$(echo "${software}" | yq --raw-output '.targetFile' -)"
-    sudo="$(echo "${software}" | yq --raw-output '.sudo' -)"
-    installCallback="$(echo "${software}" | yq --raw-output '.installCallback' -)"
+    local url=""
+    local version=""
+    local versionArg=""
+    local targetFile=""
+    local sudo=""
+    local installCallback=""
+    local softVersionCallback=""
+    # shellcheck source=/dev/null
+    source <(
+      yq -r \
+        ".softwares[] | select(.id == \"${softwareId}\") | to_entries[] | \"\(.key)=\(.value)\"" \
+        "${configFile}" | sed -E \
+        -e '/^$/d' \
+        -e 's/^([^=]+)=["\x27]*(.*)$/\1="\2/' \
+        -e 's/["\x27]*$/"/'
+    )
     if [[ -z "${installCallback}" || "${installCallback}" = "null" ]]; then
       installCallback="Github::defaultInstall"
     fi
-    softVersionCallback="$(echo "${software}" | yq --raw-output '.softVersionCallback' -)"
     if [[ -z "${softVersionCallback}" || "${softVersionCallback}" = "null" ]]; then
       softVersionCallback="Version::getCommandVersionFromPlainText"
     fi
@@ -2453,7 +2484,7 @@ processSingleSoftware() {
 
 installSoftware() {
   local softwareId="${1}"
-  local githubUrlPattern="${2}"
+  local githubUrl="${2}"
   local version="${3}"
   local versionArg="${4}"
   local targetFileArg="${5}"
@@ -2463,23 +2494,9 @@ installSoftware() {
   if [[ "${sudo}" == "null" ]]; then
     sudo=""
   fi
-  local githubUrl
-  # shellcheck disable=SC2097,SC2098
-  githubUrl="$(
-    ARCH="$(dpkg --print-architecture)" \
-    arch="${ARCH,,}" \
-    KERNEL="$(uname -s)" \
-    kernel="${KERNEL,,}" \
-    MACHINE="$(uname -m)" \
-    machine="${MACHINE,,}" \
-    OS="$(uname -s)" \
-    os="${OS,,}" \
-      eval echo "${githubUrlPattern}"
-  )"
   local targetFile
   targetFile="$(eval echo "${targetFileArg}")"
   Log::displayInfo "Installing ${softwareId}..."
-  echo "  URL pattern: ${githubUrlPattern}"
   echo "  URL: ${githubUrl}"
   echo "  Version: ${version}"
   echo "  Target file: ${targetFile}"
@@ -2521,10 +2538,26 @@ fi
 declare -a softwareIds
 # Get all software entries if no specific IDs provided
 if [[ ${#softwareIdsArg[@]} -eq 0 ]]; then
-  readarray -t softwareIds < <(yq --raw-output '.softwares[].id' "${optionConfigFile}")
+  readarray -t softwareIds < <(yq '.softwares[].id' "${optionConfigFile}")
 else
   softwareIds=("${softwareIdsArg[@]}")
 fi
+
+# shellcheck disable=SC2034
+declare -g ARCH KERNEL MACHINE OS arch kernel machine os
+ARCH="$(dpkg --print-architecture)"
+# shellcheck disable=SC2034
+arch="${ARCH,,}"
+KERNEL="$(uname -s)"
+# shellcheck disable=SC2034
+kernel="${KERNEL,,}"
+MACHINE="$(uname -m)"
+# shellcheck disable=SC2034
+machine="${MACHINE,,}"
+OS="$(uname -s)"
+# shellcheck disable=SC2034
+os="${OS,,}"
+
 if [[ ${#softwareIds[@]} -eq 1 ]]; then
   processSingleSoftware "${optionConfigFile}" "${softwareIds[0]}"
 else
