compiled gitIsBranch using go compiler

diff --git a/bin/gitIsAncestorOf b/bin/gitIsAncestorOf
--- a/bin/gitIsAncestorOf
+++ b/bin/gitIsAncestorOf
@@ -338,6 +338,27 @@ Bash::handlePipelineFailure() {
 }
 
 
+# @description run command specified
+# @arg $@ array:String[] the command to run
+# @env optionTraceVerbose int - if 1 displays the command specified before running it
+# @env optionRedirectCmdOutputs String - if set redirect command outputs to file specified
+# @exitcode command's exit code
+BashTools::runVerboseIfNeeded() {
+  # shellcheck disable=SC2154
+  if [[ "${optionTraceVerbose}" = "1" ]]; then
+    echo >&2 "+ $*"
+  fi
+  (
+    # shellcheck disable=SC2154
+    if [[ -n "${optionRedirectCmdOutputs:-}" ]]; then
+      exec >"${optionRedirectCmdOutputs:-}"
+      exec 2>"${optionRedirectCmdOutputs:-}"
+    fi
+    "$@"
+  )
+}
+
+
 # @description check if all requirements are satisfied
 # to execute dbImport commands
 Db::checkRequirements() {
@@ -1776,41 +1797,32 @@ gitIsAncestorOfCommandParse "$@"
 MAIN_FUNCTION_NAME="main"
 main() {
 
-runVerboseIfNeeded() {
-  (
-    # shellcheck disable=SC2154
-    if [[ "${optionTraceVerbose}" = "1" ]]; then
-      set -x
-    fi
-    "$@"
-  )
-}
 # shellcheck disable=SC2154
-if ! runVerboseIfNeeded git cat-file -t "${refArg}" &>/dev/null; then
+if ! optionRedirectCmdOutputs=/dev/null BashTools::runVerboseIfNeeded git cat-file -t "${refArg}"; then
   Log::displayError "Ref ${refArg} does not exists at all"
   exit 1
 fi
 # shellcheck disable=SC2154
-if ! runVerboseIfNeeded git cat-file -t "${claimedBranchArg}" &>/dev/null; then
+if ! optionRedirectCmdOutputs=/dev/null BashTools::runVerboseIfNeeded git cat-file -t "${claimedBranchArg}"; then
   Log::displayError "Ref ${claimedBranchArg} does not exists at all"
   exit 1
 fi
 
 declare refCommit claimedBranchCommit
-refCommit="$(git rev-parse "${refArg}")" || {
+refCommit="$(BashTools::runVerboseIfNeeded git rev-parse "${refArg}")" || {
   Log::displayError "Ref ${refArg} is not convertible to commit sha"
   exit 1
 }
 
-claimedBranchCommit="$(git rev-parse "${claimedBranchArg}")" || {
+claimedBranchCommit="$(BashTools::runVerboseIfNeeded git rev-parse "${claimedBranchArg}")" || {
   Log::displayError "Ref ${claimedBranchArg} is not convertible to commit sha"
   exit 1
 }
 
 declare revParse mergeBase
 # shellcheck disable=SC2154
-mergeBase="$(runVerboseIfNeeded git merge-base "${refCommit}" "${claimedBranchCommit}")"
-revParse="$(runVerboseIfNeeded git rev-parse --verify "${refCommit}")"
+mergeBase="$(BashTools::runVerboseIfNeeded git merge-base "${refCommit}" "${claimedBranchCommit}")"
+revParse="$(BashTools::runVerboseIfNeeded git rev-parse --verify "${refCommit}")"
 
 if [[ -z "${mergeBase}" || "${mergeBase}" != "${revParse}" ]]; then
   Log::displayError "Commit ${refArg} is not an ancestor of branch ${claimedBranchArg}"
