Migrated to bash-tools-framework 2.3.0
- rebuilt binaries with bash-tools-framework 2.3.0
  - Array::wrap2 performance optimizations
  - Fixed configuration loading management
  - Added Bash::handlePipelineFailure
  - Github::upgradeRelease now ignores version format
- integrated my-documents link into github page

diff --git a/bin/upgradeGithubRelease b/bin/upgradeGithubRelease
--- a/bin/upgradeGithubRelease
+++ b/bin/upgradeGithubRelease
@@ -25,10 +25,16 @@ set -o errexit
 # Command Substitution can inherit errexit option since bash v4.4
 shopt -s inherit_errexit || true
 
+# if set, and job control is not active, the shell runs the last command
+# of a pipeline not executed in the background in the current shell
+# environment.
+shopt -s lastpipe
+
 # a log is generated when a command fails
 set -o errtrace
 
-# use nullglob so that (file*.php) will return an empty array if no file matches the wildcard
+# use nullglob so that (file*.php) will return an empty array if no file
+# matches the wildcard
 shopt -s nullglob
 
 # ensure regexp are interpreted without accentuated characters
@@ -95,10 +101,12 @@ trap cleanOnExit EXIT HUP QUIT ABRT TERM
 # @description concat each element of an array with a separator
 # but wrapping text when line length is more than provided argument
 # The algorithm will try not to cut the array element if it can.
-# if an arg can be placed on current line it will be,
+# - if an arg can be placed on current line it will be,
 #   otherwise current line is printed and arg is added to the new
 #   current line
-# empty arg is interpreted as a new line.
+# - Empty arg is interpreted as a new line.
+# - Add \r to arg in order to force break line and avoid following
+#   arg to be concatenated with current arg.
 #
 # @arg $1 glue:String
 # @arg $2 maxLineLength:int
@@ -120,118 +128,102 @@ Array::wrap2() {
     return 0
   fi
 
-  eatNextSpaces() {
-    if [[ "${currentChar}" != [[:space:]] ]]; then
-      ((i--)) || true
-      return 0
-    fi
-    for (( ; i < textLength; i++)); do
-      if [[ "${text:${i}:1}" != [[:space:]] ]]; then
-        ((i--)) || true
-        break
-      fi
-    done
-  }
   printCurrentLine() {
-    echo -e "${currentLine}" | sed -E -e 's/[[:blank:]]*$//'
+    if ((isNewline == 0)) || ((previousLineEmpty == 1)); then
+      echo
+    fi
     ((isNewline = 1))
-    currentLine="${indentStr}"
+    echo -en "${indentStr}"
     ((currentLineLength = indentNextLine)) || true
   }
-  nextLine() {
-    printCurrentLine
-    eatNextSpaces
+  appendToCurrentLine() {
+    local text="$1"
+    local -i length=$2
+    ((currentLineLength += length)) || true
+    ((isNewline = 0)) || true
+    if [[ "${text: -1}" = $'\r' ]]; then
+      text="${text:0:-1}"
+      echo -en "${text%%+([[:blank:]])}"
+      printCurrentLine
+    else
+      echo -en "${text%%+([[:blank:]])}"
+    fi
   }
-  local currentLine currentChar ansiCode
-  local -i isAnsiCode currentLineLength=0 isNewline=1 textLength=0
-  local text=""
-  local arg=""
-  while (($# > 0)); do
-    arg="$1"
-    shift || true
-    if ((${#arg} == 0)) || [[ "${arg}" = $'\n' ]]; then
-      if ((isNewline == 0)); then
-        # isNewline = 0 means currentLine is not empty
+
+  (
+    local currentLine
+    local -i currentLineLength=0 isNewline=1 argLength=0
+    local -a additionalLines
+    local -i previousLineEmpty=0
+    local arg=""
+
+    while (($# > 0)); do
+      arg="$1"
+      shift || true
+
+      # replace tab by 2 spaces
+      arg="${arg//$'\t'/  }"
+      # remove trailing spaces
+      arg="${arg%[[:blank:]]}"
+      if [[ "${arg}" = $'\n' || -z "${arg}" ]]; then
         printCurrentLine
+        ((previousLineEmpty = 1))
+        continue
+      else
+        if ((previousLineEmpty == 1)); then
+          printCurrentLine
+        fi
+        ((previousLineEmpty = 0)) || true
       fi
-      echo
-      continue
-    fi
-    local textFirstLine
-    textFirstLine="$(echo "${arg}" | head -n 1)"
-    text="$(echo "${arg}" | sed -E '1d')"
-    ((textLength = ${#text})) || true
-    local textFirstLineNoAnsi
-    textFirstLineNoAnsi="$(echo "${textFirstLine}" | Filters::removeAnsiCodes)"
-    local -i textFirstLineNoAnsiLength=0
-    ((textFirstLineNoAnsiLength = ${#textFirstLineNoAnsi})) || true
+      # convert eol to args
+      mapfile -t additionalLines <<<"${arg}"
+      if ((${#additionalLines[@]} > 1)); then
+        set -- "${additionalLines[@]}" "$@"
+        continue
+      fi
 
-    if ((isNewline == 0)); then
-      glueLength="${#glue}"
-    else
-      glueLength="0"
-    fi
-    if ((currentLineLength + textFirstLineNoAnsiLength + glueLength > maxLineLength)); then
+      ((argLength = ${#arg})) || true
+
+      # empty arg
+      if ((argLength == 0)); then
+        if ((isNewline == 0)); then
+          # isNewline = 0 means currentLine is not empty
+          printCurrentLine
+        fi
+        continue
+      fi
+
       if ((isNewline == 0)); then
-        # isNewline = 0 means currentLine is not empty
-        printCurrentLine
+        glueLength="${#glue}"
+      else
+        glueLength="0"
       fi
-      # restore current arg without considering first line
-      text="${arg}"
-      ((textLength = ${#text})) || true
-    else
-      if ((isNewline == 0)); then
-        # isNewline = 0 means currentLine is not empty
-        currentLine+="${glue}"
-        ((currentLineLength += glueLength)) || true
-      fi
-      currentLine+="${textFirstLine}"
-      isNewline="0"
-      ((currentLineLength += ${#textFirstLine})) || true
-    fi
+      if ((currentLineLength + argLength + glueLength > maxLineLength)); then
+        if ((argLength + glueLength > maxLineLength)); then
+          # arg is too long to even fit on one line
+          # we have to split the arg on current and next line
+          local -i remainingLineLength
+          ((remainingLineLength = maxLineLength - currentLineLength - glueLength))
+          appendToCurrentLine "${glue:0:${glueLength}}${arg:0:${remainingLineLength}}" "$((glueLength + remainingLineLength))"
+          printCurrentLine
+          arg="${arg:${remainingLineLength}}"
+          # remove leading spaces
+          arg="${arg##[[:blank:]]}"
 
-    for ((i = 0; i < textLength; i++)); do
-      currentChar="${text:${i}:1}"
-
-      if [[ "${currentChar}" = $'\r' ]]; then
-        # ignore
-        true
-      elif [[ "${currentChar}" = "\x1b" ]]; then
-        isAnsiCode=1
-        ansiCode+="${currentChar}"
-      elif ((isAnsiCode == 1)); then
-        ansiCode+="${currentChar}"
-        if [[ "${currentChar}" =~ [mGKHF] ]]; then
-          isAnsiCode=0
-          echo -e "${ansiCode}"
-        elif [[ "${currentChar}" = $'\n' ]]; then
-          # invalid ansi code, ignore it
-          isAnsiCode=0
-          ansiCode=""
+          set -- "${arg}" "$@"
+        else
+          # the arg can fit on next line
+          printCurrentLine
+          appendToCurrentLine "${arg}" "${argLength}"
         fi
       else
-        # non ansi code
-        if [[ "${currentChar}" = $'\n' ]] || ((currentLineLength == maxLineLength)); then
-          nextLine
-        elif [[ "${currentChar}" = "\t" ]]; then
-          if ((currentLineLength + 2 <= maxLineLength)); then
-            currentLine+="  "
-            ((isNewline = 0)) || true
-            ((currentLineLength = currentLineLength + 2))
-          else
-            nextLine
-          fi
-        else
-          currentLine+="${currentChar}"
-          ((isNewline = 0)) || true
-          ((++currentLineLength))
-        fi
+        appendToCurrentLine "${glue:0:${glueLength}}${arg}" "$((glueLength + argLength))"
       fi
     done
-  done
-  if [[ "${currentLine}" != "" ]] && [[ ! "${currentLine}" =~ ^[\ \t]+$ ]]; then
-    printCurrentLine
-  fi
+    if [[ "${currentLine}" != "" ]] && [[ ! "${currentLine}" =~ ^[\ \t]+$ ]]; then
+      printCurrentLine
+    fi
+  ) | sed -E -e 's/[[:blank:]]+$//'
 }
 
 # Checks if file can be created in folder
@@ -295,10 +287,6 @@ Env::requireLoad() {
   if [[ -f "${FRAMEWORK_ROOT_DIR}/.framework-config" ]]; then
     configFiles+=("${FRAMEWORK_ROOT_DIR}/.framework-config")
   fi
-  if [[ -n "${optionBashFrameworkConfig}" && -f "${optionBashFrameworkConfig}" ]]; then
-    # shellcheck disable=SC2034
-    configFiles+=("${optionBashFrameworkConfig}")
-  fi
   configFiles+=("${optionEnvFiles[@]}")
   configFiles+=("${defaultFiles[@]}")
 
@@ -309,6 +297,14 @@ Env::requireLoad() {
       return 1
     }
   done
+}
+
+# @description create a temp file using default TMPDIR variable
+# initialized in _includes/_commonHeader.sh
+# @env TMPDIR String (default value /tmp)
+# @arg $1 templateName:String template name to use(optional)
+Framework::createTempFile() {
+  mktemp -p "${TMPDIR:-/tmp}" -t "${1:-}.XXXXXXXXXXXX"
 }
 
 # @description intermediate callback that is used by Github::upgradeRelease
@@ -696,19 +692,6 @@ Env::pathPrepend() {
   done
 }
 
-# @description remove ansi codes from input or files given as argument
-# @arg $@ files:String[] the files to filter
-# @exitcode * if one of the filter command fails
-# @stdin you can use stdin as alternative to files argument
-# @stdout the filtered content
-# @see https://en.wikipedia.org/wiki/ANSI_escape_code
-# shellcheck disable=SC2120
-Filters::removeAnsiCodes() {
-  # cspell:disable
-  sed -E 's/\x1b\[[0-9;]*[mGKHF]//g' "$@"
-  # cspell:enable
-}
-
 # @description github repository eg: kubernetes-sigs/kind
 # @arg $1 githubUrl:String eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64
 # @exitcode 1 if no matching repo found in provided url, 0 otherwise
@@ -915,7 +898,7 @@ Retry::parameterized() {
 # @stdout the version parsed
 # @require Linux::requireJqCommand
 Version::githubApiExtractVersion() {
-  jq -r ".tag_name" | Version::parse
+  jq -r ".tag_name"
 }
 
 # @description log message to file
@@ -1059,21 +1042,21 @@ optionEnvFileCallback() {
 optionInfoVerboseCallback() {
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='--verbose'
   BASH_FRAMEWORK_ARGS_VERBOSE=${__VERBOSE_LEVEL_INFO}
-  BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_INFO}
+  echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_INFO}" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
 optionDebugVerboseCallback() {
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='-vv'
   BASH_FRAMEWORK_ARGS_VERBOSE=${__VERBOSE_LEVEL_DEBUG}
-  BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_DEBUG}
+  echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_DEBUG}" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
 optionTraceVerboseCallback() {
   BASH_FRAMEWORK_ARGS_VERBOSE_OPTION='-vvv'
   BASH_FRAMEWORK_ARGS_VERBOSE=${__VERBOSE_LEVEL_TRACE}
-  BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_DEBUG}
+  echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${__LEVEL_DEBUG}" >> "${overrideEnvFile}"
 }
 
 getLevel() {
@@ -1082,10 +1065,10 @@ getLevel() {
     OFF)
       echo "${__LEVEL_OFF}"
       ;;
-    ERROR)
+    ERR | ERROR)
       echo "${__LEVEL_ERROR}"
       ;;
-    WARNING)
+    WARN | WARNING)
       echo "${__LEVEL_WARNING}"
       ;;
     INFO)
@@ -1106,7 +1089,7 @@ getVerboseLevel() {
     OFF)
       echo "${__VERBOSE_LEVEL_OFF}"
       ;;
-    ERROR | WARNING | INFO)
+    ERR | ERROR | WARN | WARNING | INFO)
       echo "${__VERBOSE_LEVEL_INFO}"
       ;;
     DEBUG)
@@ -1128,7 +1111,7 @@ optionDisplayLevelCallback() {
   logLevel="$(getLevel "${level}")"
   verboseLevel="$(getVerboseLevel "${level}")"
   BASH_FRAMEWORK_ARGS_VERBOSE=${verboseLevel}
-  BASH_FRAMEWORK_DISPLAY_LEVEL=${logLevel}
+  echo "BASH_FRAMEWORK_DISPLAY_LEVEL=${logLevel}" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1138,18 +1121,18 @@ optionLogLevelCallback() {
   logLevel="$(getLevel "${level}")"
   verboseLevel="$(getVerboseLevel "${level}")"
   BASH_FRAMEWORK_ARGS_VERBOSE=${verboseLevel}
-  BASH_FRAMEWORK_LOG_LEVEL=${logLevel}
+  echo "BASH_FRAMEWORK_LOG_LEVEL=${logLevel}" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
 optionLogFileCallback() {
   local logFile="$2"
-  BASH_FRAMEWORK_LOG_FILE="${logFile}"
+  echo "BASH_FRAMEWORK_LOG_FILE='${logFile}'" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
 optionQuietCallback() {
-  BASH_FRAMEWORK_QUIET_MODE=1
+  echo "BASH_FRAMEWORK_QUIET_MODE=1" >> "${overrideEnvFile}"
 }
 
 # shellcheck disable=SC2317 # if function is overridden
@@ -1216,15 +1199,24 @@ BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION="${BASH_FRAMEWORK_LOG_FILE_MAX_ROTATION:-5}
 EOF
 )"
 
+overrideEnvFile="$(Framework::createTempFile "overrideEnvFile")"
+
 commandOptionParseFinished() {
   # load default template framework config
-  # shellcheck disable=SC2034
   defaultEnvFile="${PERSISTENT_TMPDIR}/.framework-config"
   echo "${defaultFrameworkConfig}" > "${defaultEnvFile}"
-
-  Env::requireLoad "${defaultEnvFile}"
+  local -a files=("${defaultEnvFile}")
+  if [[ -f "${envFile}" ]]; then
+    files+=("${envFile}")
+  fi
+  # shellcheck disable=SC2154
+  if [[ -f "${optionBashFrameworkConfig}" ]]; then
+    files+=("${optionBashFrameworkConfig}")
+  fi
+  files+=("${overrideEnvFile}")
+  Env::requireLoad "${files[@]}"
   Log::requireLoad
-
+  # shellcheck disable=SC2154
   if [[ "${optionConfig}" = "1" ]]; then
     displayConfig
   fi
@@ -1506,15 +1498,15 @@ upgradeGithubReleaseCommand() {
           updateArgListQuietCallback "${options_parse_arg}"
           ;;
         # Option 16/18
-        # Option optionLogLevel --log-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
+        # Option optionLogLevel --log-level variableType String min 0 max 1 authorizedValues 'OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE' regexp ''
         --log-level)
           shift
           if (($# == 0)); then
             Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - a value needs to be specified"
             return 1
           fi
-          if [[ ! "$1" =~ OFF|ERROR|WARNING|INFO|DEBUG|TRACE ]]; then
-            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - value '$1' is not part of authorized values(OFF|ERROR|WARNING|INFO|DEBUG|TRACE)"
+          if [[ ! "$1" =~ OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE ]]; then
+            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - value '$1' is not part of authorized values(OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE)"
             return 1
           fi
           if ((options_parse_optionParsedCountOptionLogLevel >= 1)); then
@@ -1546,15 +1538,15 @@ upgradeGithubReleaseCommand() {
           updateArgListLogFileCallback "${options_parse_arg}" "${optionLogFile}"
           ;;
         # Option 18/18
-        # Option optionDisplayLevel --display-level variableType String min 0 max 1 authorizedValues 'OFF|ERROR|WARNING|INFO|DEBUG|TRACE' regexp ''
+        # Option optionDisplayLevel --display-level variableType String min 0 max 1 authorizedValues 'OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE' regexp ''
         --display-level)
           shift
           if (($# == 0)); then
             Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - a value needs to be specified"
             return 1
           fi
-          if [[ ! "$1" =~ OFF|ERROR|WARNING|INFO|DEBUG|TRACE ]]; then
-            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - value '$1' is not part of authorized values(OFF|ERROR|WARNING|INFO|DEBUG|TRACE)"
+          if [[ ! "$1" =~ OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE ]]; then
+            Log::displayError "Command ${SCRIPT_NAME} - Option ${options_parse_arg} - value '$1' is not part of authorized values(OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE)"
             return 1
           fi
           if ((options_parse_optionParsedCountOptionDisplayLevel >= 1)); then
@@ -1729,7 +1721,7 @@ upgradeGithubReleaseCommand() {
     # shellcheck disable=SC2054
     helpArray=(Set\ log\ level)
     echo -e "    $(Array::wrap2 " " 76 4 "${helpArray[@]}")"
-    echo '    Possible values: OFF|ERROR|WARNING|INFO|DEBUG|TRACE'
+    echo '    Possible values: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE'
     echo -e "  ${__HELP_OPTION_COLOR}--log-file <String>${__HELP_NORMAL} {single}"
     local -a helpArray
     # shellcheck disable=SC2054
@@ -1740,7 +1732,7 @@ upgradeGithubReleaseCommand() {
     # shellcheck disable=SC2054
     helpArray=(set\ display\ level)
     echo -e "    $(Array::wrap2 " " 76 4 "${helpArray[@]}")"
-    echo '    Possible values: OFF|ERROR|WARNING|INFO|DEBUG|TRACE'
+    echo '    Possible values: OFF|ERR|ERROR|WARN|WARNING|INFO|DEBUG|TRACE'
     echo -e """
 ${__HELP_TITLE}OPTIONS CONSTRAINTS:${__HELP_NORMAL}
 
