fixed Linters + auto Install shellcheck hadolint

diff --git a/bin/Installers/installDockerInWsl b/bin/Installers/installDockerInWsl
--- a/bin/Installers/installDockerInWsl
+++ b/bin/Installers/installDockerInWsl
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,7 +66,13 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using warning color (yellow)
 # @param {String} $1 message
 Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
+}
+
+# extract version number from github api
+# @stdin json result of github API
+Version::githubApiExtractVersion() {
+  jq -r ".tag_name" | Version::parse
 }
 
 # *Public*: run command and store data in following global variables :
@@ -97,10 +107,59 @@ Framework::run() {
   bash_framework_duration=$((end - start))
 }
 
+Github::defaultInstall() {
+  local newSoftware="$1"
+  local targetFile="$2"
+  local version="$3"
+  local installCallback=$4
+  # shellcheck disable=SC2086
+  if [[ "$(type -t ${installCallback})" = "function" ]]; then
+    ${installCallback} "${newSoftware}" "${targetFile}" "${version}"
+  else
+    mkdir -p "$(dirname "${targetFile}")"
+    mv "${newSoftware}" "${targetFile}"
+    chmod +x "${targetFile}"
+    hash -r
+  fi
+  rm -f "${newSoftware}" || true
+}
+
+# github repository eg: kubernetes-sigs/kind
+# @param {String} githubUrl eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64
+Github::extractRepoFromGithubUrl() {
+  local githubUrl="$1"
+  echo "${githubUrl}" | sed -E 's#^https://github.com/([^/]+)/([^/]+)/.*$#\1/\2#'
+}
+
+# Retrieve the latest version number of a github release using Github API using retry
+# @param {String} $1 repository in the format fchastanet/bash-tools
+#   that would match https://github.com/fchastanet/bash-tools
+# @param {String} $2 reference to a variable that will contain the result of the command
+# @output log messages about retry
+Github::getLatestRelease() {
+  local repo="$1"
+  # we need to pass the result through a reference instead of output directly
+  # because retry can output too
+  local -n resultRef=$2
+  resultRef=""
+  local resultFile
+  resultFile="$(mktemp -p "${TMPDIR:-/tmp}" -t githubLatestRelease.XXXX)"
+  # Get latest release from GitHub api
+  if Retry::default curl \
+    -o "${resultFile}" \
+    --fail \
+    --silent \
+    "https://api.github.com/repos/${repo}/releases/latest"; then
+    # shellcheck disable=SC2034
+    resultRef="$(Version::githubApiExtractVersion <"${resultFile}")"
+  fi
+  rm -f "${resultFile}"
+}
+
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Retry a command several times depending on parameters
@@ -131,6 +190,21 @@ Retry::parameterized() {
   return 0
 }
 
+# extract software version number
+# @param $1 the command that will be called with --version parameter
+Version::getCommandVersionFromPlainText() {
+  local command="$1"
+  local argVersion="${2:---version}"
+  "${command}" "${argVersion}" 2>&1 |
+    Version::parse # keep only version numbers
+}
+
+# filter to keep only version number from a string
+# @stdin the string to parse
+Version::parse() {
+  sed -nre 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' | head -n1
+}
+
 # Public: exits with message if current user is root
 #
 # **Exit**: code 1 if current user is root
@@ -152,6 +226,54 @@ declare -gx bash_framework_output
 # @param $1 {String} template (optional)
 Framework::createTempFile() {
   mktemp -p "${TMPDIR:-/tmp}" -t "$1.XXXXXXXXXXXX"
+}
+
+# upgrade given binary to latest github release using retry
+# @param {String}   targetFile target binary file (eg: /usr/local/bin/kind)
+# @param {String}   releaseUrl github release url (eg: https://github.com/kubernetes-sigs/kind/releases/download/@latestVersion@/kind-linux-amd64)
+#    the placeholder @latestVersion@ will be replaced by the latest release version
+# @param {Function} versionCallback function called to get software version (default: Version::getCommandVersionFromPlainText will call software with argument --version)
+# @param {Function} installCallback function called to install the file retrieved on github (default copy as is and set execution bit)
+# @output log messages about retry, install, upgrade
+Github::upgradeRelease() {
+  local targetFile="$1"
+  local releaseUrl="$2"
+  local argVersion="${3:---version}"
+  local versionCallback="${4:-Version::getCommandVersionFromPlainText}"
+  # shellcheck disable=SC2034
+  local installCallback="${5:-}"
+  local latestVersion
+  local repo
+
+  set -x
+  repo="$(Github::extractRepoFromGithubUrl "${releaseUrl}")"
+  Github::getLatestRelease "${repo}" latestVersion
+  Log::displayInfo "Repo ${repo} latest version found is ${latestVersion}"
+
+  local currentVersion="not existing"
+  if [[ -f "${targetFile}" ]]; then
+    currentVersion="$(${versionCallback} "${targetFile}" "${argVersion}" 2>&1 || true)"
+  fi
+  if [[ "${currentVersion}" = "${latestVersion}" ]]; then
+    Log::displayInfo "${targetFile} version ${latestVersion} already installed"
+  else
+    if [[ -z "${currentVersion}" ]]; then
+      Log::displayInfo "Installing ${targetFile} with version ${latestVersion}"
+    else
+      Log::displayInfo "Upgrading ${targetFile} from version ${currentVersion} to ${latestVersion}"
+    fi
+    local url
+    url="$(echo "${releaseUrl}" | sed -E "s/@latestVersion@/${latestVersion}/g")"
+    Log::displayInfo "Using url ${url}"
+    newSoftware=$(mktemp -p "${TMPDIR:-/tmp}" -t github.newSoftware.XXXX)
+    Retry::default curl \
+      -L \
+      -o "${newSoftware}" \
+      --fail \
+      "${url}"
+
+    Github::defaultInstall "${newSoftware}" "${targetFile}" "${latestVersion}" "${installCallback}"
+  fi
 }
 
 if [[ -t 1 || -t 2 ]]; then
@@ -194,13 +316,13 @@ fi
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using success color (bg green/fg white)
 # @param {String} $1 message
 Log::displaySuccess() {
-  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}"
+  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red) and exit immediately with error status 1
@@ -222,6 +344,15 @@ Retry::default() {
 UI::drawLine() {
   local character="${1:-#}"
   printf '%*s\n' "${COLUMNS:-$([[ -t 0 ]] && tput cols || echo)}" '' | tr ' ' "${character}"
+}
+
+# default callback called to get a version of a software
+Version::getCommandVersionFromJson() {
+  local command="$1"
+  local argVersion="${2:---version}"
+  "${command}" "${argVersion}" 2>&1 |
+    jq -r ".tag_name" | # Get tag line
+    Version::parse      # keep only version numbers
 }
 
 Assert::expectNonRootUser
@@ -312,11 +443,11 @@ fi
 Log::displayInfo "Installing docker-compose v1"
 tempDownload="$(Framework::createTempFile docker-compose)"
 [[ -f /usr/local/bin/docker-compose ]] && cp /usr/local/bin/docker-compose "${tempDownload}"
-upgradeGithubRelease \
+Github::upgradeRelease \
   "docker/compose" \
   "${tempDownload}" \
   "https://github.com/docker/compose/releases/download/v@latestVersion@/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" \
-  defaultVersion
+  Version::getCommandVersionFromJson
 
 sudo mv "${tempDownload}" /usr/local/bin/docker-compose
 sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
diff --git a/bin/cli b/bin/cli
--- a/bin/cli
+++ b/bin/cli
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,7 +66,7 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using success color (bg green/fg white)
 # @param {String} $1 message
 Log::displaySuccess() {
-  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}"
+  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
 }
 
 # *Public*: run command and store data in following global variables :
@@ -100,25 +104,25 @@ Framework::run() {
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}"
+  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using warning color (yellow)
 # @param {String} $1 message
 Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
 }
 
 # TODO use alias deactivated by default
diff --git a/bin/dbQueryAllDatabases b/bin/dbQueryAllDatabases
--- a/bin/dbQueryAllDatabases
+++ b/bin/dbQueryAllDatabases
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,7 +66,7 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using success color (bg green/fg white)
 # @param {String} $1 message
 Log::displaySuccess() {
-  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}"
+  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
 }
 
 # Internal: check if dsn file has all the mandatory variables set
@@ -209,19 +213,19 @@ Framework::trapAdd() {
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}"
+  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using warning color (yellow)
 # @param {String} $1 message
 Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
 }
 
 # TODO use alias deactivated by default
@@ -359,6 +363,12 @@ Version::compare() {
     fi
   done
   return 0
+}
+
+# filter to keep only version number from a string
+# @stdin the string to parse
+Version::parse() {
+  sed -nre 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' | head -n1
 }
 
 # Public: check if command specified exists or return 1
@@ -629,7 +639,7 @@ fi
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red) and exit immediately with error status 1
@@ -748,14 +758,15 @@ Profiles::getConfMergedList() {
 # @return 2 if command does not exist
 Version::checkMinimal() {
   local commandName="$1"
-  local commandVersion="$2"
+  local argVersion="$2"
   local minimalVersion="$3"
+  local parseVersionCallback=${4:-Version::parse}
   local help="${4:-}"
 
   Assert::commandExists "${commandName}" "${help}" || return 2
 
   local version
-  version="$(${commandVersion} 2>&1 | sed -nre 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p' | head -n1)"
+  version="$("${commandName}" "${argVersion}" 2>&1 | ${parseVersionCallback})"
 
   Log::displayDebug "check ${commandName} version ${version} against minimal ${minimalVersion}"
 
diff --git a/bin/dbQueryOneDatabase b/bin/dbQueryOneDatabase
--- a/bin/dbQueryOneDatabase
+++ b/bin/dbQueryOneDatabase
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,19 +66,19 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using success color (bg green/fg white)
 # @param {String} $1 message
 Log::displaySuccess() {
-  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}"
+  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using warning color (yellow)
 # @param {String} $1 message
 Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Internal: check if dsn file has all the mandatory variables set
@@ -181,7 +185,7 @@ Framework::trapAdd() {
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}"
+  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red) and exit immediately with error status 1
@@ -610,7 +614,7 @@ fi
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 ############################################################
diff --git a/bin/generateShellDoc b/bin/generateShellDoc
--- a/bin/generateShellDoc
+++ b/bin/generateShellDoc
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,7 +66,7 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using warning color (yellow)
 # @param {String} $1 message
 Log::displayWarning() {
-  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Public: shallow clone a repository at specific commit sha, tag or branch
@@ -85,19 +89,19 @@ Git::shallowClone() {
   local FORCE_DELETION="${4:-0}"
 
   if [[ -d "${INSTALL_DIR}/.git" ]]; then
-    Log::displayInfo >&2 "Repository ${INSTALL_DIR} already installed"
+    Log::displayInfo "Repository ${INSTALL_DIR} already installed"
   else
     if [[ -f "${INSTALL_DIR}" || -d "${INSTALL_DIR}" ]]; then
       if [[ "${FORCE_DELETION}" = "FORCE_DELETION" ]]; then
-        Log::displayWarning >&2 "Removing ${INSTALL_DIR} ..."
+        Log::displayWarning "Removing ${INSTALL_DIR} ..."
         rm -Rf "${INSTALL_DIR}" || exit 1
       else
-        Log::displayError >&2 "Destination ${INSTALL_DIR} already exists, use force option to automatically delete the destination"
+        Log::displayError "Destination ${INSTALL_DIR} already exists, use force option to automatically delete the destination"
         return 1
       fi
     fi
     (
-      Log::displayInfo >&2 "Installing ${INSTALL_DIR} ..."
+      Log::displayInfo "Installing ${INSTALL_DIR} ..."
       mkdir -p "${INSTALL_DIR}"
       cd "${INSTALL_DIR}" || exit 1
       git init >&2
@@ -115,7 +119,7 @@ ShellDoc::installRequirementsIfNeeded() {
   local tomDocInstalled
   tomDocInstalled="$(cat "${BASH_FRAMEWORK_TOMDOC_INSTALLED}")"
   if [[ "${tomDocInstalled}" != "1" ]]; then
-    (Log::displayInfo >&2 "Check if tomdoc.sh is up to date")
+    (Log::displayInfo "Check if tomdoc.sh is up to date")
     if Git::shallowClone \
       "https://github.com/fchastanet/tomdoc.sh.git" \
       "${VENDOR_DIR}/fchastanet.tomdoc.sh" \
@@ -147,13 +151,13 @@ ShellDoc::generateShellDoc() {
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # add reference to index file
diff --git a/bin/mysql2puml b/bin/mysql2puml
--- a/bin/mysql2puml
+++ b/bin/mysql2puml
@@ -16,6 +16,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -62,13 +66,13 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # Display message using debug color (grey)
 # @param {String} $1 message
 Log::displayDebug() {
-  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}"
+  echo -e "${__DEBUG_COLOR}DEBUG   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Public: list files of dir with given extension and display it as a list one by line
diff --git a/bin/waitForIt b/bin/waitForIt
--- a/bin/waitForIt
+++ b/bin/waitForIt
@@ -19,6 +19,10 @@ SRC_DIR="${ROOT_DIR}/src"
 # shellcheck disable=SC2034
 VENDOR_DIR="${ROOT_DIR}/vendor"
 # shellcheck disable=SC2034
+VENDOR_BIN_DIR="${ROOT_DIR}/vendor/bin"
+export PATH="${BIN_DIR}":"${VENDOR_BIN_DIR}":${PATH}
+
+# shellcheck disable=SC2034
 TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
 export TMPDIR
 
@@ -102,13 +106,13 @@ fi
 # Display message using error color (red)
 # @param {String} $1 message
 Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using info color (bg light blue/fg white)
 # @param {String} $1 message
 Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}" >&2
 }
 
 # Display message using error color (red) and exit immediately with error status 1
