moved shellDoc function to bash-Framework with better temp files management

diff --git a/bin/Installers/installDockerInWsl b/bin/Installers/installDockerInWsl
--- a/bin/Installers/installDockerInWsl
+++ b/bin/Installers/installDockerInWsl
@@ -12,7 +12,28 @@ CURRENT_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 BIN_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 ROOT_DIR="$(cd "${BIN_DIR}/../.." && pwd -P)"
 # shellcheck disable=SC2034
-SRC_DIR="${ROOT_DIR}/lib"
+SRC_DIR="${ROOT_DIR}/src"
+# shellcheck disable=SC2034
+VENDOR_DIR="${ROOT_DIR}/vendor"
+# shellcheck disable=SC2034
+TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
+export TMPDIR
+
+# temp dir cleaning
+cleanOnExit() {
+  rm -Rf "${TMPDIR}" >/dev/null 2>&1
+}
+trap cleanOnExit EXIT HUP QUIT ABRT TERM
+
+# @see https://unix.stackexchange.com/a/386856
+interruptManagement() {
+  # restore SIGINT handler
+  trap - INT
+  # ensure that Ctrl-C is trapped by this script and not by sub process
+  # report to the parent that we have indeed been interrupted
+  kill -s INT "$$"
+}
+trap interruptManagement INT
 
 # shellcheck disable=SC2034
 ((failures = 0)) || true
@@ -42,6 +63,38 @@ export DEBCONF_NONINTERACTIVE_SEEN=true
 # @param {String} $1 message
 Log::displayWarning() {
   echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+}
+
+# *Public*: run command and store data in following global variables :
+# * bash_framework_status the exit status of the command
+# * bash_framework_duration the duration of the command
+# * bash_framework_output the output of the command
+# redirecting error output to stdout is not supported, you can instead redirect stderr to a file if needed
+# **Arguments**:
+# * $@ command with arguments to execute
+Framework::run() {
+  # 'bash_framework_status', 'bash_framework_duration' are global variables
+  local -i start, end
+  start=$(date +%s)
+  bash_framework_status=0
+  bash_framework_output=""
+
+  local origFlags="$-"
+  set +eET
+  local origIFS="${IFS}"
+
+  # execute command
+  # shellcheck disable=SC2034
+  bash_framework_output="$("$@")"
+  # shellcheck disable=SC2034
+  bash_framework_status="$?"
+  IFS="${origIFS}"
+  set "-${origFlags}"
+
+  # calculate duration
+  end=$(date +%s)
+  # shellcheck disable=SC2034
+  bash_framework_duration=$((end - start))
 }
 
 # Display message using error color (red)
@@ -85,6 +138,20 @@ Assert::expectNonRootUser() {
   if [[ "$(id -u)" = "0" ]]; then
     Log::fatal "The script must not be run as root"
   fi
+}
+
+# global variables used by Framework::run
+declare -gx bash_framework_status
+declare -gix bash_framework_duration
+declare -gx bash_framework_output
+
+# Public: create a temp file using default TMPDIR variable
+# initialized in src/_includes/_header.tpl
+#
+# **Arguments**:
+# @param $1 {String} template (optional)
+Framework::createTempFile() {
+  mktemp -p "${TMPDIR:-/tmp}" -t "$1.XXXXXXXXXXXX"
 }
 
 if [[ -t 0 ]]; then
@@ -243,14 +310,15 @@ else
 fi
 
 Log::displayInfo "Installing docker-compose v1"
-[[ -f /usr/local/bin/docker-compose ]] && cp /usr/local/bin/docker-compose /tmp/docker-compose
+tempDownload="$(Framework::createTempFile docker-compose)"
+[[ -f /usr/local/bin/docker-compose ]] && cp /usr/local/bin/docker-compose "${tempDownload}"
 upgradeGithubRelease \
   "docker/compose" \
-  "/tmp/docker-compose" \
+  "${tempDownload}" \
   "https://github.com/docker/compose/releases/download/v@latestVersion@/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" \
   defaultVersion
 
-sudo mv /tmp/docker-compose /usr/local/bin/docker-compose
+sudo mv "${tempDownload}" /usr/local/bin/docker-compose
 sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
 
 Log::displayInfo "Installing docker-compose v2"
diff --git a/bin/dbImport b/bin/dbImport
--- a/bin/dbImport
+++ b/bin/dbImport
@@ -12,7 +12,28 @@ CURRENT_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 BIN_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 ROOT_DIR="$(cd "${BIN_DIR}/.." && pwd -P)"
 # shellcheck disable=SC2034
-SRC_DIR="${ROOT_DIR}/lib"
+SRC_DIR="${ROOT_DIR}/src"
+# shellcheck disable=SC2034
+VENDOR_DIR="${ROOT_DIR}/vendor"
+# shellcheck disable=SC2034
+TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
+export TMPDIR
+
+# temp dir cleaning
+cleanOnExit() {
+  rm -Rf "${TMPDIR}" >/dev/null 2>&1
+}
+trap cleanOnExit EXIT HUP QUIT ABRT TERM
+
+# @see https://unix.stackexchange.com/a/386856
+interruptManagement() {
+  # restore SIGINT handler
+  trap - INT
+  # ensure that Ctrl-C is trapped by this script and not by sub process
+  # report to the parent that we have indeed been interrupted
+  kill -s INT "$$"
+}
+trap interruptManagement INT
 
 # shellcheck disable=SC2034
 ((failures = 0)) || true
@@ -37,6 +58,12 @@ export DEBIAN_FRONTEND=noninteractive
 export DEBCONF_NONINTERACTIVE_SEEN=true
 
 # FUNCTIONS
+
+# Display message using success color (bg green/fg white)
+# @param {String} $1 message
+Log::displaySuccess() {
+  echo -e "${__SUCCESS_COLOR}SUCCESS - ${1}${__RESET_COLOR}"
+}
 
 # Internal: check if dsn file has all the mandatory variables set
 # Mandatory variables are: HOSTNAME, USER, PASSWORD, PORT
@@ -115,6 +142,28 @@ Framework::run() {
   end=$(date +%s)
   # shellcheck disable=SC2034
   bash_framework_duration=$((end - start))
+}
+
+# appends a command to a trap
+#
+# - 1st arg:  code to add
+# - remaining args:  names of traps to modify
+#
+Framework::trapAdd() {
+  local trapAddCmd="$1"
+  shift || Log::fatal "${FUNCNAME[0]} usage error"
+  # helper fn to get existing trap command from output
+  # of trap -p
+  extract_trap_cmd() { printf '%s\n' "$3"; }
+  for trapAddName in "$@"; do
+    trap -- "$(
+      # print existing trap command with newline
+      eval "extract_trap_cmd $(trap -p "${trapAddName}")"
+      # print the new trap command
+      printf '%s\n' "${trapAddCmd}"
+    )" "${trapAddName}" ||
+      Log::fatal "unable to add to trap ${trapAddName}"
+  done
 }
 
 # Display message using debug color (grey)
@@ -507,6 +556,15 @@ declare -gx bash_framework_status
 declare -gix bash_framework_duration
 declare -gx bash_framework_output
 
+# Public: create a temp file using default TMPDIR variable
+# initialized in src/_includes/_header.tpl
+#
+# **Arguments**:
+# @param $1 {String} template (optional)
+Framework::createTempFile() {
+  mktemp -p "${TMPDIR:-/tmp}" -t "$1.XXXXXXXXXXXX"
+}
+
 ## Initialize some default variables
 ## List of variables
 ## * BASH_FRAMEWORK_INITIALIZED=1 lazy initialization
@@ -604,28 +662,6 @@ Framework::loadEnv() {
   export BASH_FRAMEWORK_INITIALIZED=1
 
   set +o allexport
-}
-
-# appends a command to a trap
-#
-# - 1st arg:  code to add
-# - remaining args:  names of traps to modify
-#
-Framework::trapAdd() {
-  local trapAddCmd="$1"
-  shift || Log::fatal "${FUNCNAME[0]} usage error"
-  # helper fn to get existing trap command from output
-  # of trap -p
-  extract_trap_cmd() { printf '%s\n' "$3"; }
-  for trapAddName in "$@"; do
-    trap -- "$(
-      # print existing trap command with newline
-      eval "extract_trap_cmd $(trap -p "${trapAddName}")"
-      # print the new trap command
-      printf '%s\n' "${trapAddCmd}"
-    )" "${trapAddName}" ||
-      Log::fatal "unable to add to trap ${trapAddName}"
-  done
 }
 
 if [[ -t 0 ]]; then
@@ -1016,9 +1052,8 @@ if [[ -n "${TABLES}" ]]; then
 fi
 
 if [[ "${PROFILE}" = 'default' && -n "${TABLES}" ]]; then
-  PROFILE_COMMAND=$(mktemp -p "${TMPDIR:-/tmp}" -t "profileCmd.XXXXXXXXXXXX")
+  PROFILE_COMMAND=$(Framework::createTempFile "profileCmd.XXXXXXXXXXXX")
   chmod +x "${PROFILE_COMMAND}"
-  Framework::trapAdd "rm -f \"${PROFILE_COMMAND}\" 2>/dev/null || true" ERR EXIT
   PROFILE_MSG_INFO="only ${TABLES} will be imported"
   (
     echo '#!/usr/bin/env bash'
@@ -1099,7 +1134,7 @@ if [[ "${DOWNLOAD_DUMP}" = "1" ]]; then
       Log::fatal "unable to get information on S3 object : ${S3_URL}"
     }
     Log::displayInfo "Download dump from ${S3_URL} ..."
-    TMPDIR="${TEMP_FOLDER:-/tmp}" aws s3 cp "${S3_URL}" "${REMOTE_DB_DUMP_TEMP_FILE}" || {
+    TMPDIR="${TMDIR:-/tmp}" aws s3 cp "${S3_URL}" "${REMOTE_DB_DUMP_TEMP_FILE}" || {
       Log::fatal "unable to download dump from S3 : ${S3_URL}"
     }
   else
diff --git a/bin/generateShellDoc b/bin/generateShellDoc
--- a/bin/generateShellDoc
+++ b/bin/generateShellDoc
@@ -12,7 +12,28 @@ CURRENT_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 BIN_DIR=$(cd "$(readlink -e "${BASH_SOURCE[0]%/*}")" && pwd -P)
 ROOT_DIR="$(cd "${BIN_DIR}/.." && pwd -P)"
 # shellcheck disable=SC2034
-SRC_DIR="${ROOT_DIR}/lib"
+SRC_DIR="${ROOT_DIR}/src"
+# shellcheck disable=SC2034
+VENDOR_DIR="${ROOT_DIR}/vendor"
+# shellcheck disable=SC2034
+TMPDIR="$(mktemp -d -p "${TMPDIR:-/tmp}" -t bash-framework-$$-XXXXXX)"
+export TMPDIR
+
+# temp dir cleaning
+cleanOnExit() {
+  rm -Rf "${TMPDIR}" >/dev/null 2>&1
+}
+trap cleanOnExit EXIT HUP QUIT ABRT TERM
+
+# @see https://unix.stackexchange.com/a/386856
+interruptManagement() {
+  # restore SIGINT handler
+  trap - INT
+  # ensure that Ctrl-C is trapped by this script and not by sub process
+  # report to the parent that we have indeed been interrupted
+  kill -s INT "$$"
+}
+trap interruptManagement INT
 
 # shellcheck disable=SC2034
 ((failures = 0)) || true
@@ -37,6 +58,151 @@ export DEBIAN_FRONTEND=noninteractive
 export DEBCONF_NONINTERACTIVE_SEEN=true
 
 # FUNCTIONS
+
+# Display message using warning color (yellow)
+# @param {String} $1 message
+Log::displayWarning() {
+  echo -e "${__WARNING_COLOR}WARN    - ${1}${__RESET_COLOR}"
+}
+
+# Public: shallow clone a repository at specific commit sha, tag or branch
+# or update repo if already exists
+#
+# **Arguments**:
+# * $1 repository
+# * $2 Install dir
+# * $3 revision commit sha, tag or branch
+# * $4 put "FORCE_DELETION" to force directory deletion if directory exists and it's not a git repository (default: 0)
+#     USE THIS OPTION WITH CAUTION !!! as the directory will be deleted without any prompt
+#
+# **Return**:
+# * code !=0 if git failure or directory not writable
+# * code=1 if destination dir already exists and force option is not 1
+Git::shallowClone() {
+  local REPO="$1"
+  local INSTALL_DIR="$2"
+  local REVISION="$3"
+  local FORCE_DELETION="${4:-0}"
+
+  if [[ -d "${INSTALL_DIR}/.git" ]]; then
+    Log::displayInfo >&2 "Repository ${INSTALL_DIR} already installed"
+  else
+    if [[ -f "${INSTALL_DIR}" || -d "${INSTALL_DIR}" ]]; then
+      if [[ "${FORCE_DELETION}" = "FORCE_DELETION" ]]; then
+        Log::displayWarning >&2 "Removing ${INSTALL_DIR} ..."
+        rm -Rf "${INSTALL_DIR}" || exit 1
+      else
+        Log::displayError >&2 "Destination ${INSTALL_DIR} already exists, use force option to automatically delete the destination"
+        return 1
+      fi
+    fi
+    (
+      Log::displayInfo >&2 "Installing ${INSTALL_DIR} ..."
+      mkdir -p "${INSTALL_DIR}"
+      cd "${INSTALL_DIR}" || exit 1
+      git init >&2
+      git remote add origin "${REPO}" >&2
+    )
+  fi
+  (
+    cd "${INSTALL_DIR}" || exit 1
+    git -c advice.detachedHead=false fetch --progress --depth 1 origin "${REVISION}" >&2
+    git reset --hard FETCH_HEAD >&2
+  )
+}
+
+ShellDoc::installRequirementsIfNeeded() {
+  local tomDocInstalled
+  tomDocInstalled="$(cat "${BASH_FRAMEWORK_TOMDOC_INSTALLED}")"
+  if [[ "${tomDocInstalled}" != "1" ]]; then
+    (Log::displayInfo >&2 "Check if tomdoc.sh is up to date")
+    if Git::shallowClone \
+      "https://github.com/fchastanet/tomdoc.sh.git" \
+      "${VENDOR_DIR}/fchastanet.tomdoc.sh" \
+      "master" \
+      "FORCE_DELETION"; then
+      echo "1" >"${BASH_FRAMEWORK_TOMDOC_INSTALLED}"
+    else
+      Log::fatal "unable to install tomdoc.sh library"
+    fi
+  fi
+}
+
+# extract shDoc from file
+#
+# @param {String} $1 currentDir
+# @param {String} $2 relativeFile
+# @output the shell documentation in markdown format
+ShellDoc::generateShellDoc() {
+  local currentDir="$1"
+  local relativeFile="$2"
+
+  ShellDoc::installRequirementsIfNeeded
+  (
+    cd "${currentDir}" || exit 1
+    "${ROOT_DIR}/vendor/fchastanet.tomdoc.sh/tomdoc.sh" "${relativeFile}"
+  )
+}
+
+# Display message using error color (red)
+# @param {String} $1 message
+Log::displayError() {
+  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
+}
+
+# Display message using info color (bg light blue/fg white)
+# @param {String} $1 message
+Log::displayInfo() {
+  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
+}
+
+# add reference to index file
+# @param {String} $1 indexFile
+# @param {String} $2 mdRelativeFile
+# @param {String} $3 title
+ShellDoc::appendDocToIndex() {
+  local indexFile="$1"
+  local mdRelativeFile="$2"
+  local title="$3"
+
+  echo "* [${title}](${mdRelativeFile})" >>"${indexFile}"
+}
+
+# generate shell doc file
+#
+# @param {String} $1 currentDir
+# @param {String} $2 relativeFile the file from which the markdown file will be generated
+# @param {String} $3 targetDocFile the markdown file generated using tomdoc
+# @return 0 if file has been generated, 1 if file is empty or error
+# if generated doc is empty, targetDocFile is deleted if it was existing
+ShellDoc::generateShellDocFile() {
+  local currentDir="$1"
+  local relativeFile="$2"
+  local targetDocFile="$3"
+
+  (
+    local doc
+    doc="$(ShellDoc::generateShellDoc "${currentDir}" "${relativeFile}")"
+    if [[ -n "${doc}" ]]; then
+      echo "${doc}" >"${targetDocFile}"
+      return 0
+    else
+      # empty doc
+      rm -f "${targetDocFile}" || true
+      return 1
+    fi
+  )
+}
+
+# Checks if file can be created in folder
+# The file does not need to exist
+Assert::fileWritable() {
+  local file="$1"
+  local dir
+  dir="$(dirname "${file}")"
+
+  [[ -w "${dir}" ]]
+}
 
 if [[ -t 0 ]]; then
   # check colors applicable https://misc.flogisoft.com/bash/tip_colors_and_formatting
@@ -75,18 +241,6 @@ else
   export readonly __HELP_NORMAL=''
 fi
 
-# Display message using error color (red)
-# @param {String} $1 message
-Log::displayError() {
-  echo -e "${__ERROR_COLOR}ERROR   - ${1}${__RESET_COLOR}"
-}
-
-# Display message using info color (bg light blue/fg white)
-# @param {String} $1 message
-Log::displayInfo() {
-  echo -e "${__INFO_COLOR}INFO    - ${1}${__RESET_COLOR}"
-}
-
 # Display message using error color (red) and exit immediately with error status 1
 # @param {String} $1 message
 Log::fatal() {
@@ -94,65 +248,14 @@ Log::fatal() {
   exit 1
 }
 
-# extract shDoc from file
-#
-# @param {String} $1 currentDir
-# @param {String} $2 relativeFile
-# @output the shell documentation in markdown format
-generateShellDoc() {
-  local currentDir="$1"
-  local relativeFile="$2"
-
-  (
-    cd "${currentDir}" || exit 1
-    "${ROOT_DIR}/vendor/fchastanet.tomdoc.sh/tomdoc.sh" "${relativeFile}"
-  )
-}
-
-# generate shell doc file
-#
-# @param {String} $1 currentDir
-# @param {String} $2 relativeFile the file from which the markdown file will be generated
-# @param {String} $3 targetDocFile the markdown file generated using tomdoc
-# @return 0 if file has been generated, 1 if file is empty or error
-# if generated doc is empty, targetDocFile is deleted if it was existing
-generateShellDocFile() {
-  local currentDir="$1"
-  local relativeFile="$2"
-  local targetDocFile="$3"
-
-  (
-    local doc
-    doc="$(generateShellDoc "${currentDir}" "${relativeFile}")"
-    if [[ -n "${doc}" ]]; then
-      echo "${doc}" >"${targetDocFile}"
-      return 0
-    else
-      # empty doc
-      rm -f "${targetDocFile}" || true
-      return 1
-    fi
-  )
-}
-
-# add reference to index file
-# @param {String} $1 indexFile
-# @param {String} $2 title
-# @param {String} $3 mdRelativeFile
-appendDocToIndex() {
-  local indexFile="$1"
-  local title="$2"
-  local mdRelativeFile="$3"
-
-  echo "* [${relativeFile}](doc/${basenameNoExtension}.md)" >>"${indexFile}"
-  echo "* [${title}](${mdRelativeFile})" >>"${indexFile}"
-}
+# shellcheck disable=SC2034
+BASH_FRAMEWORK_TOMDOC_INSTALLED=$(mktemp -p "${TMPDIR:-/tmp}" -t tomdocInstalled.XXXX)
 
 # generate doc + index
 # @param {String} $1 fromDir
 # @param {String} $2 docDir
 # @param {String} $3 indexFile
-generateShellDocsFromDir() {
+ShellDoc::generateShellDocsFromDir() {
   local fromDir="$1"
   local docDir="$2"
   local indexFile="$3"
@@ -173,8 +276,8 @@ generateShellDocsFromDir() {
     # generate markdown file from shell file
     Log::displayInfo "generate markdown doc for ${relativeFile} in ${targetDocFile}"
 
-    if generateShellDocFile "${fromDir}" "${relativeFile}" "${targetDocFile}"; then
-      appendDocToIndex "${indexFile}" "${relativeFile}" "${basenameNoExtension}"
+    if ShellDoc::generateShellDocFile "${fromDir}" "${relativeFile}" "${targetDocFile}"; then
+      ShellDoc::appendDocToIndex "${indexFile}" "${relativeFile}" "${basenameNoExtension}"
     fi
   done < <(cd "${fromDir}" && find . -name "*.sh" | sort)
 }
@@ -224,19 +327,35 @@ while true; do
   shift || true
 done
 
+if (($# != 3)); then
+  Log::fatal "yous should provide exactly 3 parameters"
+fi
+
 declare fromDir="$1"
 declare docDir="$2"
 declare indexFile="$3"
-
-if [[ ! -d "${fromDir}" ]]; then
-  Log::fatal "Directory ${fromDir} does not exists"
-fi
 
 fromDir="$(realpath "${fromDir}")"
 docDir="$(realpath "${docDir}")"
 indexFile="$(realpath "${indexFile}")"
 
-generateShellDocsFromDir \
+if [[ ! -d "${fromDir}" ]]; then
+  Log::fatal "From directory '${fromDir}' does not exists"
+fi
+if [[ ! -r "${fromDir}" ]]; then
+  Log::fatal "From directory '${fromDir}' is not readable"
+fi
+
+mkdir -p "${docDir}" || true
+if [[ ! -w "${docDir}" ]]; then
+  Log::fatal "From directory '${fromDir}' is not writeable"
+fi
+
+if ! Assert::fileWritable "${indexFile}"; then
+  Log::fatal "File ${indexFile} is not writeable"
+fi
+
+ShellDoc::generateShellDocsFromDir \
   "${fromDir}" \
   "${docDir}" \
   "${indexFile}"
