debug

diff --git a/bin/Installers/installDockerInWsl b/bin/Installers/installDockerInWsl
--- a/bin/Installers/installDockerInWsl
+++ b/bin/Installers/installDockerInWsl
@@ -158,7 +158,8 @@ Github::upgradeRelease() {
   local repo
 
   repo="$(Github::extractRepoFromGithubUrl "${releaseUrl}")"
-  Github::getLatestRelease "${repo}" latestVersion
+  Github::getLatestRelease "${repo}" latestVersion ||
+    Log::fatal "Repo ${repo} latest version not found"
   Log::displayInfo "Repo ${repo} latest version found is ${latestVersion}"
 
   local currentVersion="not existing"
@@ -417,7 +418,10 @@ Github::getLatestRelease() {
     "https://api.github.com/repos/${repo}/releases/latest"; then
     # shellcheck disable=SC2034
     resultRef="$(Version::githubApiExtractVersion <"${resultFile}")"
+    return 0
   fi
+  # display curl result in case of failure
+  cat >&2 "${resultFile}"
   rm -f "${resultFile}"
 }
 
